"""
Check that the legacy survey file written with the points on the reference
trajectory (survey_output_ref_points.tfs, generated by
000b_gm_survey_data_m2_line.py) is compatible with the output of the MAD-X
survey on the same line.

For each element, the file has a zero-length ``DRIFT_<i>`` row with the
entrance point and a row with the element name with the exit point. The exit
rows are compared with the corresponding MAD-X rows, the entrance rows with
the MAD-X row preceding the element (exit of the previous node).
"""

import numpy as np
import xtrack as xt
from cpymad.madx import Madx

# Legacy survey file written by xsuite
sv_xs = xt.load('survey_output_ref_points.tfs')

# Survey with MAD-X (same line, same strengths, same initial conditions)
mad = Madx(stdout=False)
mad.call('M2_MTN3p8_v6_notilt.seq')
mad.call('M2_MTN3p8_v5_notilt.str')
mad.input('beam, particle=proton, pc=160; use, sequence=M2;')

X0, Y0, Z0 = -677.24488, 2441.56985, 4605.8619
theta0, phi0, psi0 = 1.406046 - np.pi / 2, -0.000358, 0
mad.input(f'survey, x0={X0}, y0={Y0}, z0={Z0}, '
          f'theta0={theta0}, phi0={phi0}, psi0={psi0};')
sv_mad = mad.table.survey
mad_names = [nn.split(':')[0].upper() for nn in sv_mad.name]

# Rows of the xsuite file: exit points (element names) and entrance points
# (zero-length DRIFT_<i> rows preceding them)
i_exit = np.array([ii for ii, nn in enumerate(sv_xs.name)
                   if not nn.startswith('DRIFT_')])
i_entry = i_exit - 1
assert np.all([nn.startswith('DRIFT_') for nn in sv_xs.name[i_entry]])
assert len(i_exit) > 100

# Corresponding rows in the MAD-X table
i_mad_exit = np.array([mad_names.index(nn) for nn in sv_xs.name[i_exit]])
i_mad_entry = i_mad_exit - 1

cols = ['s', 'l', 'angle', 'x', 'y', 'z', 'theta', 'phi', 'psi',
        'globaltilt', 'tilt', 'slot_id']
for col in cols:
    v_xs = getattr(sv_xs, col)
    v_mad = np.array(sv_mad[col])
    # Exit points
    assert np.allclose(v_xs[i_exit], v_mad[i_mad_exit], rtol=0, atol=1e-8), (
        f'exit {col}: max difference '
        f'{np.max(np.abs(v_xs[i_exit] - v_mad[i_mad_exit]))}')
    # Entrance points (L, ANGLE, TILT, SLOT_ID are zero in the DRIFT rows)
    if col in ['x', 'y', 'z', 'theta', 'phi', 'psi', 'globaltilt', 's']:
        assert np.allclose(v_xs[i_entry], v_mad[i_mad_entry],
                           rtol=0, atol=1e-8), (
            f'entrance {col}: max difference '
            f'{np.max(np.abs(v_xs[i_entry] - v_mad[i_mad_entry]))}')
    else:
        assert np.all(v_xs[i_entry] == 0)

print('Legacy survey (reference trajectory) identical to MAD-X survey')
