"""
Plot the convergence order of the different integrators available for the
`Magnet` element, tracking a large-angle bend.
"""
import matplotlib.pyplot as plt
import numpy as np

import xtrack as xt
from xtrack import Magnet

# Number of kicks generated by the yoshida integrators per "slice"
N_KICKS_PER_SLICE = {
    'teapot': 1,
    'uniform': 1,
    'yoshida-4': 3,
    'yoshida-6': 7,
    'yoshida-8': 15,
}

CONVERGENCE_SLICES = {
    'teapot': [2**i for i in range(5, 19)],
    'uniform': [2**i for i in range(5, 19)],
    'yoshida-4': [16, 64, 256, 512, 1024],
    'yoshida-6': [4, 8, 16, 32, 64],
    'yoshida-8': [2, 4, 8, 16],
}

EXPECTED_ORDER = {
    'teapot': 2,
    'uniform': 2,
    'yoshida-4': 4,
    'yoshida-6': 6,
    'yoshida-8': 8,
}

COORDS = ('x', 'px', 'y', 'py', 'delta')


def max_rel_error(particle, exact_coords):
    return max(
        abs(getattr(particle, coord)[0] - exact_coords[coord])
        / abs(exact_coords[coord])
        for coord in COORDS
    )


bend_kwargs = {
    'length': 1.0,
    'angle': np.pi / 10,
    'edge_entry_active': False,
    'edge_exit_active': False,
}

exact = Magnet(model='bend-kick-bend', **bend_kwargs, integrator='uniform', num_multipole_kicks=1)
p0 = xt.Particles(
    kinetic_energy0=1e9, x=3e-3, px=1e-3, y=2e-3, py=-1e-3, delta=2e-3,
)
p_exact = p0.copy()
exact.track(p_exact)
bend_exact_coords = {coord: getattr(p_exact, coord)[0] for coord in COORDS}

fig, ax = plt.subplots(figsize=(7, 5))

for integrator, num_slices in CONVERGENCE_SLICES.items():
    stages = N_KICKS_PER_SLICE[integrator]
    errors = []
    for n_slices in num_slices:
        mm = Magnet(
            model='rot-kick-rot-low-order',
            integrator=integrator,
            num_multipole_kicks=stages * n_slices,
            **bend_kwargs,
        )
        p_slice = p0.copy()
        mm.track(p_slice)
        errors.append(max_rel_error(p_slice, bend_exact_coords))

    slope, _ = np.polyfit(np.log(num_slices), np.log(errors), 1)
    order = -slope

    line, = ax.loglog(
        num_slices, errors, 'o-',
        label=f'{integrator} (expected {EXPECTED_ORDER[integrator]}, '
              f'observed {order:.2f})',
    )

ax.set_xlabel('Number of slices')
ax.set_ylabel('Max relative error vs. exact bend-kick-bend')
ax.set_title('Integrator convergence order (large-angle bend)')
ax.legend()
ax.grid(True, which='both', ls=':')
fig.tight_layout()
plt.show()
