/* Generated by Cython 3.0.10 */

#ifndef __PYX_HAVE__xtrack__sequence__parser
#define __PYX_HAVE__xtrack__sequence__parser

#include "Python.h"

#ifndef __PYX_HAVE_API__xtrack__sequence__parser

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void yyerror(YYLTYPE *, yyscan_t, char const *);
__PYX_EXTERN_C PyObject *py_integer(yyscan_t, long);
__PYX_EXTERN_C PyObject *py_float(yyscan_t, double);
__PYX_EXTERN_C PyObject *py_string(yyscan_t, char const *);
__PYX_EXTERN_C PyObject *py_unary_op(yyscan_t, char const *, PyObject *);
__PYX_EXTERN_C PyObject *py_binary_op(yyscan_t, char const *, PyObject *, PyObject *);
__PYX_EXTERN_C PyObject *py_assign(yyscan_t, char const *, PyObject *);
__PYX_EXTERN_C PyObject *py_call_func(yyscan_t, char const *, PyObject *);
__PYX_EXTERN_C PyObject *py_arrow(yyscan_t, char const *, char const *);
__PYX_EXTERN_C PyObject *py_identifier_atom(yyscan_t, char const *, YYLTYPE);
__PYX_EXTERN_C void py_set_value(yyscan_t, PyObject *, YYLTYPE);
__PYX_EXTERN_C PyObject *py_reference(yyscan_t, PyObject *, char const *, YYLTYPE);
__PYX_EXTERN_C PyObject *py_set_ref(yyscan_t, PyObject *, PyObject *);
__PYX_EXTERN_C PyObject *py_start_beamline(yyscan_t, char const *, PyObject *, YYLTYPE);
__PYX_EXTERN_C void py_end_beamline(yyscan_t, PyObject *);
__PYX_EXTERN_C void py_add_element(yyscan_t, PyObject *, PyObject *);
__PYX_EXTERN_C PyObject *py_clone(yyscan_t, char const *, PyObject *);
__PYX_EXTERN_C void py_clone_global(yyscan_t, PyObject *);
__PYX_EXTERN_C PyObject *py_command(yyscan_t, char const *, PyObject *, YYLTYPE);
__PYX_EXTERN_C void py_add_command(yyscan_t, PyObject *, PyObject *, YYLTYPE);
__PYX_EXTERN_C PyObject *__pyx_fuse_0py_numeric(yyscan_t, double);
__PYX_EXTERN_C PyObject *__pyx_fuse_1py_numeric(yyscan_t, long);

#endif /* !__PYX_HAVE_API__xtrack__sequence__parser */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initparser(void);
#else
/* WARNING: Use PyImport_AppendInittab("parser", PyInit_parser) instead of calling PyInit_parser directly from Python 3.5 */
PyMODINIT_FUNC PyInit_parser(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"parser\", PyInit_parser) instead of calling PyInit_parser directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"parser\", PyInit_parser) instead of calling PyInit_parser directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"parser\", PyInit_parser) instead of calling PyInit_parser directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_parser_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_parser() __PYX_WARN_IF_PyInit_parser_INIT_CALLED(PyInit_parser())
#endif
#endif

#endif /* !__PYX_HAVE__xtrack__sequence__parser */
