"""Utilities to generate API documentation text from categorized metadata."""

from __future__ import annotations

import inspect
import re


def _underline(text: str, char: str) -> str:
    return char * len(text)


def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug or "section"


def _wrap_friendly(text: str) -> str:
    # Add zero-width break opportunities for long snake_case names.
    return text.replace("_", "_\u200b")


def _first_sentence(doc: str | None) -> str:
    if not doc:
        return "TBD"
    paragraph_lines = []
    for raw_line in doc.splitlines():
        line = raw_line.strip()
        if not line:
            if paragraph_lines:
                break
            continue
        paragraph_lines.append(line)

    if not paragraph_lines:
        return "TBD"

    paragraph = " ".join(paragraph_lines)
    head = paragraph.split(".", 1)[0].strip()
    out = head if head else paragraph
    return _wrap_friendly(out) if out else "TBD"


def generate_categorized_class_rst(
    cls,
    *,
    title: str | None = None,
    include_properties: bool = True,
    include_toc: bool = False,
    include_summary_table: bool = True,
) -> str:
    """Generate RST for a categorized class API.

    Parameters
    ----------
    cls : type
        Class exposing ``__api_categories__`` metadata.
    title : str, optional
        Document title. If omitted, ``"<ClassName> API (Categorized)"`` is used.
    include_properties : bool, optional
        If True, include property sections.
    include_toc : bool, optional
        If True, include a local table of contents at the beginning.
    include_summary_table : bool, optional
        If True, include a compact summary table of categories and members.

    Returns
    -------
    str
        Full reStructuredText content.
    """
    categories = getattr(cls, "__api_categories__", None)
    if categories is None:
        raise ValueError(
            f"{cls.__name__} has no __api_categories__ metadata. "
            "Ensure API categorization is initialized."
        )

    full_name = f"{cls.__module__}.{cls.__name__}"
    title = title or f"{cls.__name__} API (Categorized)"

    out = []
    out.append(f"{title}\n")
    out.append(f"{_underline(title, '=')}\n\n")
    out.append(
        f".. This file content is autogenerated from ``{full_name}.__api_categories__``.\n\n"
    )
    if include_toc:
        out.append(".. contents:: Table of Contents\n")
        out.append("   :local:\n")
        out.append("   :depth: 2\n\n")
    if include_summary_table:
        out.append("Summary\n")
        out.append("-------\n\n")
        out.append(".. raw:: html\n\n")
        out.append("   <style>\n")
        out.append("   table.line-api-summary-table { width: 100%; table-layout: fixed; }\n")
        out.append("   table.line-api-summary-table th,\n")
        out.append("   table.line-api-summary-table td {\n")
        out.append("     white-space: normal !important;\n")
        out.append("     overflow-wrap: anywhere;\n")
        out.append("     word-break: break-word;\n")
        out.append("   }\n")
        out.append("   </style>\n\n")
        for category in categories:
            cat_name = category["name"]
            methods = category.get("methods", [])
            properties = category.get("properties", [])
            cat_slug = _slugify(cat_name)
            cat_label = f"line-api-{cat_slug}"

            out.append(f".. list-table:: :ref:`{cat_name} <{cat_label}>`\n")
            out.append("   :class: line-api-summary-table\n")
            out.append("   :header-rows: 1\n")
            out.append("   :width: 100%\n")
            out.append("   :widths: 40 60\n\n")
            out.append("   * - Member\n")
            out.append("     - Description\n")

            for method in methods:
                member_obj = getattr(cls, method)
                desc = _first_sentence(inspect.getdoc(member_obj))
                method_text = _wrap_friendly(f"{method}(...)")
                out.append(
                    f"   * - :ref:`{method_text} <{cat_label}-method-{_slugify(method)}>`\n"
                )
                out.append(f"     - {desc}\n")

            for prop in properties:
                member_obj = getattr(cls, prop)
                desc = _first_sentence(inspect.getdoc(member_obj))
                prop_text = _wrap_friendly(prop)
                out.append(
                    f"   * - :ref:`{prop_text} <{cat_label}-property-{_slugify(prop)}>`\n"
                )
                out.append(f"     - {desc}\n")

            if not methods and not properties:
                out.append("   * - -\n")
                out.append("     - -\n")
            out.append("\n")
        out.append("\n")

    for category in categories:
        cat_name = category["name"]
        methods = category.get("methods", [])
        properties = category.get("properties", [])
        cat_slug = _slugify(cat_name)
        cat_label = f"line-api-{cat_slug}"
        methods_label = f"{cat_label}-methods"
        properties_label = f"{cat_label}-properties"

        out.append(f".. _{cat_label}:\n\n")
        out.append(f"{cat_name}\n")
        out.append(f"{_underline(cat_name, '-')}\n\n")

        if methods:
            out.append(f".. _{methods_label}:\n\n")
            out.append("Methods\n")
            out.append("~~~~~~~\n\n")
            for method in methods:
                out.append(f".. _{cat_label}-method-{_slugify(method)}:\n\n")
                out.append(f".. automethod:: {full_name}.{method}\n\n")

        if include_properties and properties:
            out.append(f".. _{properties_label}:\n\n")
            out.append("Properties\n")
            out.append("~~~~~~~~~~\n\n")
            for prop in properties:
                out.append(f".. _{cat_label}-property-{_slugify(prop)}:\n\n")
                out.append(f".. autoproperty:: {full_name}.{prop}\n\n")

    return "".join(out)


def generate_line_rst(
    *,
    title: str = "Line API (Categorized)",
    include_properties: bool = True,
    include_toc: bool = False,
    include_summary_table: bool = True,
) -> str:
    """Generate RST documentation for ``xtrack.Line`` categories."""
    from .line import Line

    return generate_categorized_class_rst(
        Line,
        title=title,
        include_properties=include_properties,
        include_toc=include_toc,
        include_summary_table=include_summary_table,
    )
