"""Regenerate masses.py offline from the adjacent, versioned source excerpts."""

import argparse
from decimal import Decimal
import hashlib
import json
from math import sqrt
from pathlib import Path


DATA_DIR = Path(__file__).resolve().parent
OUTPUT = DATA_DIR.parents[1] / 'xtrack' / 'particles' / 'masses.py'


def read_sources():
    metadata = json.loads((DATA_DIR / 'sources.json').read_text())
    for name, source in metadata.items():
        digest = hashlib.sha256((DATA_DIR / name).read_bytes()).hexdigest()
        if digest != source['excerpt_sha256']:
            raise ValueError(f'Source checksum mismatch: {name}')

    constants = {}
    for line in (DATA_DIR / 'codata2022_selected.txt').read_text().splitlines()[11:]:
        quantity = line[:60].strip().removesuffix(' mass energy equivalent in MeV')
        value = Decimal(line[60:85].replace(' ', '')) * 10**6
        uncertainty = Decimal(line[85:110].replace(' ', '')) * 10**6
        constants[quantity] = (value, uncertainty)

    binding = {}
    for line in (DATA_DIR / 'nist_binding_energies.txt').read_text().splitlines():
        fields = [field.strip() for field in line.split('|')]
        if len(fields) != 6 or not fields[0].isdigit():
            continue
        z, spectrum, charge, energy, uncertainty, _ = fields
        assert charge == '0'
        assert energy.startswith('[') and energy.endswith(']')
        binding[spectrum.split()[0]] = (
            int(z), Decimal(energy[1:-1]), Decimal(uncertainty))

    atoms = []
    for line in (DATA_DIR / 'ame2020_selected.txt').read_text().splitlines()[36:]:
        z, a = int(line[9:14]), int(line[14:19])
        element = line[20:23].strip()
        # AME stores the integer part in u, and the fractional part in micro-u.
        fractional = line[110:123].strip()
        mass_u = (Decimal(line[106:109])
                  + Decimal(fractional.replace('#', '.')) / 10**6)
        uncertainty_u = Decimal(line[123:135].replace('#', '.')) / 10**6
        atoms.append((element, z, a, mass_u, uncertainty_u, '#' in fractional))
    return constants, binding, atoms


def render():
    constants, binding, atoms = read_sources()
    text = '''# copyright ############################### #
# This file is part of the Xtrack Package.  #
# Copyright (c) CERN, 2026.                 #
# ######################################### #

"""Rest energies m*c**2 in eV (mass parameters in eV/c**2).

All isotope masses are for fully stripped ground-state nuclei.
U_MASS_EV is the atomic mass unit, defined from the NEUTRAL carbon-12 atom.

Generated by test_data/particle_masses/generate_masses.py. See
test_data/particle_masses/README.md and the source excerpts there for provenance,
calculations and approximations.
Regenerate from the repository root:
    python test_data/particle_masses/generate_masses.py

Sources:
  AME2020: https://doi.org/10.1088/1674-1137/abddaf (Eq. 1)
  CODATA 2022: https://physics.nist.gov/cuu/Constants/Table/allascii.txt
  NIST ASD 5.12: https://doi.org/10.18434/T4W30F (total electron binding energies)
  PDG 2024: https://pdg.lbl.gov/2024/listings/particle_properties.html

Conversion: M_nucleus*c**2 = M_atom[u]*U_MASS_EV - Z*ELECTRON_MASS_EV + B_e.
B_e is positive and includes ALL electrons. The same NIST elemental B_e is
used for all isotopes; isotope shifts of B_e are neglected. The listed sigma
is an approximate quadrature of input uncertainties, ignoring correlations
and the unquantified isotope-shift error (not a certified total uncertainty).
AME '#' marks extrapolated atomic masses. Decimal places are computational
guard digits, not a claim of experimental accuracy. Converted isotope masses
are rounded to 0.1 eV; direct CODATA values retain their published precision.
"""

# Direct CODATA 2022 values; no electron subtraction for these bare nuclei.
'''
    direct = [
        ('ELECTRON', 'electron'), ('MUON', 'muon'), ('PROTON', 'proton'),
        ('DEUTERON', 'deuteron'), ('TRITON', 'triton'),
        ('He3', 'helion'), ('He4', 'alpha particle'), ('NEUTRON', 'neutron'),
        ('U', 'atomic mass constant energy equivalent in MeV'),
    ]
    for name, key in direct:
        value, uncertainty = constants[key]
        value_str = format(value, 'f').rstrip('0').rstrip('.')
        if '.' not in value_str:
            value_str += '.0'
        sigma_str = format(uncertainty, 'f').rstrip('0').rstrip('.')
        text += (f'{name + "_MASS_EV":<17} = {value_str:>18}'
                 f'  # CODATA 2022; sigma = {sigma_str} eV\n')
    text += '''
# Meson values retained from the previous table (PDG 2024); photon is exact.
PHOTON_MASS_EV    =            0.0
PION_MASS_EV      =    139570390.0  # sigma = 180 eV
KAON_MASS_EV      =    493677000.0  # sigma = 15000 eV
PION0_MASS_EV     =    134976800.0  # sigma = 500 eV
KAON0_MASS_EV     =    497611000.0  # sigma = 13000 eV
'''
    u, sigma_u = constants['atomic mass constant energy equivalent in MeV']
    electron, sigma_electron = constants['electron']
    last_element = None
    for element, z, a, atom_u, sigma_atom_u, extrapolated in sorted(
            atoms, key=lambda row: (row[1], row[2])):
        binding_z, be, sigma_be = binding[element]
        assert z == binding_z
        if element != last_element:
            text += (f'\n# {element}: Z = {z}; NIST ASD B_e = {be} eV; '
                     f'sigma(B_e) = {sigma_be} eV.\n')
            last_element = element
        nucleus = atom_u * u - z * electron + be
        sigma = sqrt(float((u * sigma_atom_u)**2 + (atom_u * sigma_u)**2
                           + (z * sigma_electron)**2 + sigma_be**2))
        flag = ' #' if extrapolated else ''
        text += (f'{element + str(a) + "_MASS_EV":<17} = {nucleus:18.1f}'
                 f'  # AME atom: {atom_u} u{flag}; approx sigma = {sigma:.2g} eV\n')
    return text


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true',
                        help='Check that masses.py matches the saved sources.')
    args = parser.parse_args()
    text = render()
    if args.check:
        if OUTPUT.read_text() != text:
            raise SystemExit('masses.py is out of date; rerun this script without --check.')
        print('masses.py matches the saved source data.')
    else:
        OUTPUT.write_text(text)
        print(f'Wrote {OUTPUT}')


if __name__ == '__main__':
    main()
