// This file is generated by _generate_slice_elements_c_code.py
// Do not edit it directly.


    // copyright ############################### //
    // This file is part of the Xtrack Package.  //
    // Copyright (c) CERN, 2023.                 //
    // ######################################### //

    #ifndef XTRACK_DRIFT_SLICE_CAVITY_H
    #define XTRACK_DRIFT_SLICE_CAVITY_H

    #include <headers/track.h>
    #include <beam_elements/elements_src/track_drift.h>


    GPUFUN
    void DriftSliceCavity_track_local_particle(
            DriftSliceCavityData el,
            LocalParticle* part0
    ) {

        double weight = DriftSliceCavityData_get_weight(el);
        double length;
        if (LocalParticle_check_track_flag(part0, XS_FLAG_BACKTRACK)) {
            length = -weight * DriftSliceCavityData_get__parent_length(el); // m
        }
        else {
            length = weight * DriftSliceCavityData_get__parent_length(el); // m
        }

        START_PER_PARTICLE_BLOCK(part0, part);
            Drift_single_particle(part, length);
        END_PER_PARTICLE_BLOCK;
    }

    #endif
    