// This file is generated by _generate_slice_elements_c_code.py
// Do not edit it directly.


        // copyright ############################### //
        // This file is part of the Xtrack Package.  //
        // Copyright (c) CERN, 2023.                 //
        // ######################################### //

        #ifndef XTRACK_DRIFT_SLICE_RBEND_H
        #define XTRACK_DRIFT_SLICE_RBEND_H

        #include "xtrack/headers/track.h"
        #include "xtrack/beam_elements/elements_src/track_drift.h"


        GPUFUN
        void DriftSliceRBend_track_local_particle(
                DriftSliceRBendData el,
                LocalParticle* part0
        ) {

            double weight = DriftSliceRBendData_get_weight(el);
            int64_t rbend_model = DriftSliceRBendData_get__parent_rbend_model(el);
            double full_length;
            double length_drift;
            if (rbend_model == 2) { // straight-body
                full_length = DriftSliceRBendData_get__parent_length_straight(el);
                length_drift = full_length * weight;
            }
            else {
                full_length = DriftSliceRBendData_get__parent_length(el);
                length_drift = full_length * weight;
            }


            if (LocalParticle_check_track_flag(part0, XS_FLAG_BACKTRACK)) {
                length_drift *= -1; // 
            }

            if (rbend_model == 2) { // straight-body
                // Force exact drift
                START_PER_PARTICLE_BLOCK(part0, part);
                    Drift_single_particle_exact(part, length_drift);
                END_PER_PARTICLE_BLOCK;
            }
            else {
                START_PER_PARTICLE_BLOCK(part0, part);
                    Drift_single_particle(part, length_drift);
                END_PER_PARTICLE_BLOCK;
            }
        }

        #endif
        