// This file is generated by _generate_slice_elements_c_code.py
// Do not edit it directly.

// copyright ############################### //
// This file is part of the Xtrack Package.  //
// Copyright (c) CERN, 2023.                 //
// ######################################### //

#ifndef XTRACK_THICK_SLICE_RBEND_H
#define XTRACK_THICK_SLICE_RBEND_H

#include <headers/track.h>
#include <beam_elements/elements_src/track_magnet.h>
#include <beam_elements/elements_src/default_magnet_config.h>

GPUFUN
void ThickSliceRBend_track_local_particle(
    ThickSliceRBendData el,
    LocalParticle* part0
) {

    track_magnet_particles(
        /*weight*/                ThickSliceRBendData_get_weight(el),
        /*part0*/                 part0,
        /*length*/                ThickSliceRBendData_get__parent_length(el),
        /*order*/                 ThickSliceRBendData_get__parent_order(el),
        /*inv_factorial_order*/   ThickSliceRBendData_get__parent_inv_factorial_order(el),
        /*knl*/                   ThickSliceRBendData_getp1__parent_knl(el, 0),
        /*ksl*/                   ThickSliceRBendData_getp1__parent_ksl(el, 0),
        /*num_multipole_kicks*/   ThickSliceRBendData_get__parent_num_multipole_kicks(el),
        /*model*/                 ThickSliceRBendData_get__parent_model(el),
        /*default_model*/         RBEND_DEFAULT_MODEL,
        /*integrator*/            ThickSliceRBendData_get__parent_integrator(el),
        /*default_integrator*/    RBEND_DEFAULT_INTEGRATOR,
        /*radiation_flag*/        ThickSliceRBendData_get_radiation_flag(el),
        /*radiation_flag_parent*/ ThickSliceRBendData_get__parent_radiation_flag(el),
        /*radiation_record*/      NULL,
        /*delta_taper*/           ThickSliceRBendData_get_delta_taper(el),
        /*h*/                     ThickSliceRBendData_get__parent_h(el),
        /*hxl*/                   0.,
        /*k0*/                    ThickSliceRBendData_get__parent_k0(el),
        /*k1*/                    ThickSliceRBendData_get__parent_k1(el),
        /*k2*/                    0.,
        /*k3*/                    0.,
        /*k0s*/                   0.,
        /*k1s*/                   0.,
        /*k2s*/                   0.,
        /*k3s*/                   0.,
        /*ks*/                    0.,
        /*dks_ds*/                0.,
        /*rbend_model*/           ThickSliceRBendData_get__parent_rbend_model(el),
        /*rbend_shift*/           ThickSliceRBendData_get__parent_rbend_shift(el),
        /*body_active*/           1,
        /*edge_entry_active*/     0,
        /*edge_exit_active*/      0,
        /*edge_entry_model*/      0,
        /*edge_exit_model*/       0,
        /*edge_entry_angle*/      0,
        /*edge_exit_angle*/       0,
        /*edge_entry_angle_fdown*/0,
        /*edge_exit_angle_fdown*/ 0,
        /*edge_entry_fint*/       0,
        /*edge_exit_fint*/        0,
        /*edge_entry_hgap*/       0,
        /*edge_exit_hgap*/        0
    );
}

#endif // XTRACK_THICK_SLICE_RBEND_H