// This file is generated by _generate_slice_elements_c_code.py
// Do not edit it directly.

// copyright ############################### //
// This file is part of the Xtrack Package.  //
// Copyright (c) CERN, 2021.                 //
// ######################################### //

#ifndef XTRACK_THICK_SLICE_CAVITY_H
#define XTRACK_THICK_SLICE_CAVITY_H

#include <beam_elements/elements_src/track_rf.h>

GPUFUN
void ThickSliceCavity_track_local_particle(ThickSliceCavityData el, LocalParticle* part0)
{
    track_rf_particles(
        /*weight*/                ThickSliceCavityData_get_weight(el),
        /*part0*/                 part0,
        /*length*/                ThickSliceCavityData_get__parent_length(el),
        /*voltage*/               ThickSliceCavityData_get__parent_voltage(el),
        /*frequency*/             ThickSliceCavityData_get__parent_frequency(el),
        /*lag*/                   ThickSliceCavityData_get__parent_lag(el),
        /*transverse_voltage*/    0.,
        /*transverse_lag*/        0.,
        /*absolute_time*/         ThickSliceCavityData_get__parent_absolute_time(el),
        /*order*/                 -1, // not used here
        /*knl*/                   NULL,
        /*ksl*/                   NULL,
        /*pn*/                    NULL,
        /*ps*/                    NULL,
        /*num_kicks*/             ThickSliceCavityData_get__parent_num_kicks(el),
        /*model*/                 ThickSliceCavityData_get__parent_model(el),
        /*default_model*/         6, // drift-kick-drift-expanded
        /*integrator*/            ThickSliceCavityData_get__parent_integrator(el),
        /*default_integrator*/    3, // Uniform
        /*radiation_flag*/        0, // not used here
        /*radiation_flag_parent*/ 0, // not used here
        /*lag_taper*/             ThickSliceCavityData_get__parent_lag_taper(el),
        /*body_active*/           1,
        /*edge_entry_active*/     0, // not used here
        /*edge_exit_active*/      0  // not used here
    );

}

#endif  // XTRACK_THICK_SLICE_CAVITY_H