// This file is generated by _generate_slice_elements_c_code.py
// Do not edit it directly.

// copyright ############################### //
// This file is part of the Xtrack Package.  //
// Copyright (c) CERN, 2023.                 //
// ######################################### //

#ifndef XTRACK_THICK_SLICE_QUADRUPOLE_H
#define XTRACK_THICK_SLICE_QUADRUPOLE_H

#include "xtrack/headers/track.h"
#include "xtrack/beam_elements/elements_src/track_magnet.h"
#include "xtrack/beam_elements/elements_src/default_magnet_config.h"

GPUFUN
void ThickSliceQuadrupole_track_local_particle(
        ThickSliceQuadrupoleData el,
        LocalParticle* part0
) {

    track_magnet_particles(
        /*weight*/                ThickSliceQuadrupoleData_get_weight(el),
        /*part0*/                 part0,
        /*length*/                ThickSliceQuadrupoleData_get__parent_length(el),
        /*order*/                 ThickSliceQuadrupoleData_get__parent_order(el),
        /*inv_factorial_order*/   ThickSliceQuadrupoleData_get__parent_inv_factorial_order(el),
        /*knl*/                   ThickSliceQuadrupoleData_getp1__parent_knl(el, 0),
        /*ksl*/                   ThickSliceQuadrupoleData_getp1__parent_ksl(el, 0),
        /*order_rel*/             ThickSliceQuadrupoleData_len__parent_knl_rel(el) - 1, // order_rel is derived from the length of knl_rel and ksl_rel arrays
      /*inv_factorial_order_rel*/ 1. / (tgamma(ThickSliceQuadrupoleData_len__parent_knl_rel(el))), // 1 / (order_rel)! = 1 / tgamma(order_rel + 1)
        /*knl_rel*/               ThickSliceQuadrupoleData_getp1__parent_knl_rel(el, 0),
        /*ksl_rel*/               ThickSliceQuadrupoleData_getp1__parent_ksl_rel(el, 0),
        /*rel_ref_strength*/      ThickSliceQuadrupoleData_get__parent_length(el) * ((ThickSliceQuadrupoleData_get__parent_main_is_skew(el)) ? ThickSliceQuadrupoleData_get__parent_k1s(el) : ThickSliceQuadrupoleData_get__parent_k1(el)),
        /*num_multipole_kicks*/   ThickSliceQuadrupoleData_get__parent_num_multipole_kicks(el),
        /*model*/                 ThickSliceQuadrupoleData_get__parent_model(el),
        /*default_model*/         QUADRUPOLE_DEFAULT_MODEL,
        /*integrator*/            ThickSliceQuadrupoleData_get__parent_integrator(el),
        /*default_integrator*/    QUADRUPOLE_DEFAULT_INTEGRATOR,
        /*radiation_flag*/        ThickSliceQuadrupoleData_get_radiation_flag(el),
        /*radiation_flag_parent*/ ThickSliceQuadrupoleData_get__parent_radiation_flag(el),
        /*radiation_record*/      NULL,
        /*delta_taper*/           ThickSliceQuadrupoleData_get_delta_taper(el),
        /*h*/                     0.,
        /*hxl*/                   0.,
        /*k0*/                    0.,
        /*k1*/                    ThickSliceQuadrupoleData_get__parent_k1(el),
        /*k2*/                    0.,
        /*k3*/                    0.,
        /*k0s*/                   0.,
        /*k1s*/                   ThickSliceQuadrupoleData_get__parent_k1s(el),
        /*k2s*/                   0.,
        /*k3s*/                   0.,
        /*ks*/                    0.,
        /*dks_ds*/                0.,
        /*x0_solenoid*/           0.,
        /*y0_solenoid*/           0.,
        /*rbend_model*/           -1, // not rbend
     /*rbend_compensate_sagitta*/ 0,  // not rbend
        /*rbend_shift*/           0., // not rbend
        /*rbend_angle_diff*/      0., // not rbend
        /*length_straight*/       0., // not rbend
        /*body_active*/           1,
        /*edge_entry_active*/     0,
        /*edge_exit_active*/      0,
        /*edge_entry_model*/      0,
        /*edge_exit_model*/       0,
        /*edge_entry_angle*/      0.,
        /*edge_exit_angle*/       0.,
        /*edge_entry_angle_fdown*/0.,
        /*edge_exit_angle_fdown*/ 0.,
        /*edge_entry_fint*/       0.,
        /*edge_exit_fint*/        0.,
        /*edge_entry_hgap*/       0.,
        /*edge_exit_hgap*/        0.
    );
}

#endif // XTRACK_THICK_SLICE_QUADRUPOLE_H