// This file is generated by _generate_slice_elements_c_code.py
// Do not edit it directly.

// copyright ############################### //
// This file is part of the Xtrack Package.  //
// Copyright (c) CERN, 2023.                 //
// ######################################### //

#ifndef XTRACK_THICK_SLICE_UNIFORM_SOLENOID_H
#define XTRACK_THICK_SLICE_UNIFORM_SOLENOID_H

#include <headers/track.h>
#include <beam_elements/elements_src/track_magnet.h>
#include <beam_elements/elements_src/default_magnet_config.h>

GPUFUN
void ThickSliceUniformSolenoid_track_local_particle(
        ThickSliceUniformSolenoidData el,
        LocalParticle* part0
) {

    track_magnet_particles(
        /*weight*/                ThickSliceUniformSolenoidData_get_weight(el),
        /*part0*/                 part0,
        /*length*/                ThickSliceUniformSolenoidData_get__parent_length(el),
        /*order*/                 ThickSliceUniformSolenoidData_get__parent_order(el),
        /*inv_factorial_order*/   ThickSliceUniformSolenoidData_get__parent_inv_factorial_order(el),
        /*knl*/                   ThickSliceUniformSolenoidData_getp1__parent_knl(el, 0),
        /*ksl*/                   ThickSliceUniformSolenoidData_getp1__parent_ksl(el, 0),
        /*num_multipole_kicks*/   ThickSliceUniformSolenoidData_get__parent_num_multipole_kicks(el),
        /*model*/                 -2, // sol-kick-sol
        /*default_model*/         0, // unused
        /*integrator*/            ThickSliceUniformSolenoidData_get__parent_integrator(el),
        /*default_integrator*/    SOLENOID_DEFAULT_INTEGRATOR,
        /*radiation_flag*/        ThickSliceUniformSolenoidData_get_radiation_flag(el),
        /*radiation_flag_parent*/ ThickSliceUniformSolenoidData_get__parent_radiation_flag(el),
        /*radiation_record*/      NULL,
        /*delta_taper*/           ThickSliceUniformSolenoidData_get_delta_taper(el),
        /*h*/                     0.,
        /*hxl*/                   0.,
        /*k0*/                    0.,
        /*k1*/                    0.,
        /*k2*/                    0.,
        /*k3*/                    0.,
        /*k0s*/                   0.,
        /*k1s*/                   0.,
        /*k2s*/                   0.,
        /*k3s*/                   0.,
        /*ks*/                    ThickSliceUniformSolenoidData_get__parent_ks(el),
        /*dks_ds*/                0.,
        /*rbend_model*/           -1, // not rbend
        /*rbend_shift*/           0.,
        /*body_active*/           1,
        /*edge_entry_active*/     0,
        /*edge_exit_active*/      0,
        /*edge_entry_model*/      3, // only ax ay cancellation0,
        /*edge_exit_model*/       3, // only ax ay cancellation0,
        /*edge_entry_angle*/      0.,
        /*edge_exit_angle*/       0.,
        /*edge_entry_angle_fdown*/0.,
        /*edge_exit_angle_fdown*/ 0.,
        /*edge_entry_fint*/       0.,
        /*edge_exit_fint*/        0.,
        /*edge_entry_hgap*/       0.,
        /*edge_exit_hgap*/        0.
    );
}

#endif // XTRACK_THICK_SLICE_UNIFORM_SOLENOID_H