// This file is generated by _generate_slice_elements_c_code.py
// Do not edit it directly.

// copyright ############################### //
// This file is part of the Xtrack Package.  //
// Copyright (c) CERN, 2023.                 //
// ######################################### //

#ifndef XTRACK_THICK_SLICE_BEND_H
#define XTRACK_THICK_SLICE_BEND_H

#include "xtrack/headers/track.h"
#include "xtrack/headers/factorial.h"
#include "xtrack/beam_elements/elements_src/track_magnet.h"
#include "xtrack/beam_elements/elements_src/default_magnet_config.h"

GPUFUN
void ThickSliceBend_track_local_particle(
        ThickSliceBendData el,
        LocalParticle* part0
) {

    track_magnet_particles(
        /*weight*/                ThickSliceBendData_get_weight(el),
        /*part0*/                 part0,
        /*length*/                ThickSliceBendData_get__parent_length(el),
        /*order*/                 ThickSliceBendData_get__parent_order(el),
        /*inv_factorial_order*/   ThickSliceBendData_get__parent_inv_factorial_order(el),
        /*knl*/                   ThickSliceBendData_getp1__parent_knl(el, 0),
        /*ksl*/                   ThickSliceBendData_getp1__parent_ksl(el, 0),
        /*order_rel*/             ThickSliceBendData_len__parent_knl_rel(el) - 1, // order_rel is derived from the length of knl_rel and ksl_rel arrays
      /*inv_factorial_order_rel*/ one_over_factorial(ThickSliceBendData_len__parent_knl_rel(el) - 1), // 1 / (order_rel)!
        /*knl_rel*/               ThickSliceBendData_getp1__parent_knl_rel(el, 0),
        /*ksl_rel*/               ThickSliceBendData_getp1__parent_ksl_rel(el, 0),
        /*rel_ref_strength*/      ThickSliceBendData_get__parent_k0(el) * ThickSliceBendData_get__parent_length(el),
        /*num_multipole_kicks*/   ThickSliceBendData_get__parent_num_multipole_kicks(el),
        /*model*/                 ThickSliceBendData_get__parent_model(el),
        /*default_model*/         BEND_DEFAULT_MODEL,
        /*integrator*/            ThickSliceBendData_get__parent_integrator(el),
        /*default_integrator*/    BEND_DEFAULT_INTEGRATOR,
        /*radiation_flag*/        ThickSliceBendData_get_radiation_flag(el),
        /*radiation_flag_parent*/ ThickSliceBendData_get__parent_radiation_flag(el),
        /*radiation_record*/      NULL,
        /*delta_taper*/           ThickSliceBendData_get_delta_taper(el),
        /*h*/                     ThickSliceBendData_get__parent_h(el),
        /*hxl*/                   0.,
        /*k0*/                    ThickSliceBendData_get__parent_k0(el),
        /*k1*/                    ThickSliceBendData_get__parent_k1(el),
        /*k2*/                    ThickSliceBendData_get__parent_k2(el),
        /*k3*/                    0.,
        /*k0s*/                   0.,
        /*k1s*/                   0.,
        /*k2s*/                   0.,
        /*k3s*/                   0.,
        /*ks*/                    0.,
        /*dks_ds*/                0.,
        /*x0_solenoid*/           0.,
        /*y0_solenoid*/           0.,
        /*rbend_model*/           -1, // not rbend
     /*rbend_compensate_sagitta*/ 0,  // not rbend
        /*rbend_shift*/           0., // not rbend
        /*rbend_angle_diff*/      0., // not rbend
        /*length_straight*/       0., // not rbend
        /*body_active*/           1,
        /*edge_entry_active*/     0,
        /*edge_exit_active*/      0,
        /*edge_entry_model*/      0,
        /*edge_exit_model*/       0,
        /*edge_entry_angle*/      0,
        /*edge_exit_angle*/       0,
        /*edge_entry_angle_fdown*/0,
        /*edge_exit_angle_fdown*/ 0,
        /*edge_entry_fint*/       0,
        /*edge_exit_fint*/        0,
        /*edge_entry_hgap*/       0,
        /*edge_exit_hgap*/        0
    );

}

#endif // XTRACK_TRUEBEND_H