// This file is generated by _generate_slice_elements_c_code.py
// Do not edit it directly.

// copyright ############################### //
// This file is part of the Xtrack Package.  //
// Copyright (c) CERN, 2021.                 //
// ######################################### //

#ifndef XTRACK_THIN_SLICE_CRABCAVITY_H
#define XTRACK_THIN_SLICE_CRABCAVITY_H

#include <beam_elements/elements_src/track_rf.h>

GPUFUN
void ThinSliceCrabCavity_track_local_particle(ThinSliceCrabCavityData el, LocalParticle* part0)
{
    track_rf_particles(
        /*weight*/                ThinSliceCrabCavityData_get_weight(el),
        /*part0*/                 part0,
        /*length*/                ThinSliceCrabCavityData_get__parent_length(el),
        /*voltage*/               0,
        /*frequency*/             ThinSliceCrabCavityData_get__parent_frequency(el),
        /*lag*/                   0.,
        /*transverse_voltage*/    ThinSliceCrabCavityData_get__parent_crab_voltage(el),
        /*transverse_lag*/        ThinSliceCrabCavityData_get__parent_lag(el),
        /*absolute_time*/         ThinSliceCrabCavityData_get__parent_absolute_time(el),
        /*order*/                 -1, // not used here
        /*knl*/                   NULL,
        /*ksl*/                   NULL,
        /*pn*/                    NULL,
        /*ps*/                    NULL,
        /*num_kicks*/             1, // kick only
        /*model*/                 -1, // kick only
        /*default_model*/         6, // drift-kick-drift-expanded
        /*integrator*/            3, // uniform
        /*default_integrator*/    3, // Uniform
        /*radiation_flag*/        0, // not used here
        /*radiation_flag_parent*/ 0, // not used here
        /*lag_taper*/             ThinSliceCrabCavityData_get__parent_lag_taper(el),
        /*body_active*/           1,
        /*edge_entry_active*/     0, // not used here
        /*edge_exit_active*/      0  // not used here
    );

}

#endif  // XTRACK_THIN_SLICE_CRABCAVITY_H