// This file is generated by _generate_slice_elements_c_code.py
// Do not edit it directly.

// copyright ############################### //
// This file is part of the Xtrack Package.  //
// Copyright (c) CERN, 2023.                 //
// ######################################### //

#ifndef XTRACK_EXIT_SLICE_RBEND_H
#define XTRACK_EXIT_SLICE_RBEND_H

#include <headers/track.h>
#include <beam_elements/elements_src/track_magnet.h>
#include <beam_elements/elements_src/default_magnet_config.h>

GPUFUN
void ThinSliceRBendExit_track_local_particle(
    ThinSliceRBendExitData el,
    LocalParticle* part0
) {

    track_magnet_particles(
        /*weight*/                0., // unused
        /*part0*/                 part0,
        /*length*/                ThinSliceRBendExitData_get__parent_length(el),
        /*order*/                 ThinSliceRBendExitData_get__parent_order(el),
        /*inv_factorial_order*/   ThinSliceRBendExitData_get__parent_inv_factorial_order(el),
        /*knl*/                   ThinSliceRBendExitData_getp1__parent_knl(el, 0),
        /*ksl*/                   ThinSliceRBendExitData_getp1__parent_ksl(el, 0),
        /*num_multipole_kicks*/   0, // unused
        /*model*/                 0, // unused
        /*default_model*/         RBEND_DEFAULT_MODEL,
        /*integrator*/            0, // unused
        /*default_integrator*/    RBEND_DEFAULT_INTEGRATOR,
        /*radiation_flag*/        ThinSliceRBendExitData_get_radiation_flag(el),
        /*radiation_flag_parent*/ ThinSliceRBendExitData_get__parent_radiation_flag(el),
        /*radiation_record*/      NULL,
        /*delta_taper*/           ThinSliceRBendExitData_get_delta_taper(el),
        /*h*/                     ThinSliceRBendExitData_get__parent_h(el),
        /*hxl*/                   0.,
        /*k0*/                    ThinSliceRBendExitData_get__parent_k0(el),
        /*k1*/                    ThinSliceRBendExitData_get__parent_k1(el),
        /*k2*/                    0.,
        /*k3*/                    0.,
        /*k0s*/                   0.,
        /*k1s*/                   0.,
        /*k2s*/                   0.,
        /*k3s*/                   0.,
        /*ks*/                    0.,
        /*dks_ds*/                0.,
        /*rbend_model*/           ThinSliceRBendExitData_get__parent_rbend_model(el),
        /*rbend_shift*/           ThinSliceRBendExitData_get__parent_rbend_shift(el),
        /*body_active*/           0, // disabled
        /*edge_entry_active*/     0,
        /*edge_exit_active*/      ThinSliceRBendExitData_get__parent_edge_exit_active(el),
        /*edge_entry_model*/      0,
        /*edge_exit_model*/       ThinSliceRBendExitData_get__parent_edge_exit_model(el),
        /*edge_entry_angle*/      0,
        /*edge_exit_angle*/       ThinSliceRBendExitData_get__parent_edge_exit_angle(el),
        /*edge_entry_angle_fdown*/0,
        /*edge_exit_angle_fdown*/ ThinSliceRBendExitData_get__parent_edge_exit_angle_fdown(el),
        /*edge_entry_fint*/       0,
        /*edge_exit_fint*/        ThinSliceRBendExitData_get__parent_edge_exit_fint(el),
        /*edge_entry_hgap*/       0,
        /*edge_exit_hgap*/        ThinSliceRBendExitData_get__parent_edge_exit_hgap(el)
    );
}

#endif // XTRACK_EXIT_SLICE_RBEND_H