// This file is generated by _generate_slice_elements_c_code.py
// Do not edit it directly.

// copyright ############################### //
// This file is part of the Xtrack Package.  //
// Copyright (c) CERN, 2023.                 //
// ######################################### //

#ifndef XTRACK_ENTRY_SLICE_BEND_H
#define XTRACK_ENTRY_SLICE_BEND_H

#include <headers/track.h>
#include <beam_elements/elements_src/track_magnet.h>
#include <beam_elements/elements_src/default_magnet_config.h>

GPUFUN
void ThinSliceBendEntry_track_local_particle(
        ThinSliceBendEntryData el,
        LocalParticle* part0
) {

    track_magnet_particles(
        /*weight*/                0., // unused
        /*part0*/                 part0,
        /*length*/                ThinSliceBendEntryData_get__parent_length(el),
        /*order*/                 ThinSliceBendEntryData_get__parent_order(el),
        /*inv_factorial_order*/   ThinSliceBendEntryData_get__parent_inv_factorial_order(el),
        /*knl*/                   ThinSliceBendEntryData_getp1__parent_knl(el, 0),
        /*ksl*/                   ThinSliceBendEntryData_getp1__parent_ksl(el, 0),
        /*num_multipole_kicks*/   0, // unused
        /*model*/                 0, // unused
        /*default_model*/         BEND_DEFAULT_MODEL,
        /*integrator*/            0, // unused
        /*default_integrator*/    BEND_DEFAULT_INTEGRATOR,
        /*radiation_flag*/        ThinSliceBendEntryData_get_radiation_flag(el),
        /*radiation_flag_parent*/ ThinSliceBendEntryData_get__parent_radiation_flag(el),
        /*radiation_record*/      NULL,
        /*delta_taper*/           ThinSliceBendEntryData_get_delta_taper(el),
        /*h*/                     ThinSliceBendEntryData_get__parent_h(el),
        /*hxl*/                   0.,
        /*k0*/                    ThinSliceBendEntryData_get__parent_k0(el),
        /*k1*/                    ThinSliceBendEntryData_get__parent_k1(el),
        /*k2*/                    0.,
        /*k3*/                    0.,
        /*k0s*/                   0.,
        /*k1s*/                   0.,
        /*k2s*/                   0.,
        /*k3s*/                   0.,
        /*ks*/                    0.,
        /*dks_ds*/                0.,
        /*rbend_model*/           -1, // not rbend
        /*rbend_shift*/           0.,
        /*body_active*/           0, // disabled
        /*edge_entry_active*/     ThinSliceBendEntryData_get__parent_edge_entry_active(el),
        /*edge_exit_active*/      0,
        /*edge_entry_model*/      ThinSliceBendEntryData_get__parent_edge_entry_model(el),
        /*edge_exit_model*/       0,
        /*edge_entry_angle*/      ThinSliceBendEntryData_get__parent_edge_entry_angle(el),
        /*edge_exit_angle*/       0,
        /*edge_entry_angle_fdown*/ThinSliceBendEntryData_get__parent_edge_entry_angle_fdown(el),
        /*edge_exit_angle_fdown*/ 0,
        /*edge_entry_fint*/       ThinSliceBendEntryData_get__parent_edge_entry_fint(el),
        /*edge_exit_fint*/        0,
        /*edge_entry_hgap*/       ThinSliceBendEntryData_get__parent_edge_entry_hgap(el),
        /*edge_exit_hgap*/        0
    );

}

#endif // XTRACK_TRUEBEND_H