// This file is generated by _generate_slice_elements_c_code.py
// Do not edit it directly.

// copyright ############################### //
// This file is part of the Xtrack Package.  //
// Copyright (c) CERN, 2023.                 //
// ######################################### //

#ifndef XTRACK_EXIT_SLICE_QUADRUPOLE_H
#define XTRACK_EXIT_SLICE_QUADRUPOLE_H

#include <headers/track.h>
#include <beam_elements/elements_src/track_magnet.h>
#include <beam_elements/elements_src/default_magnet_config.h>

GPUFUN
void ThinSliceQuadrupoleExit_track_local_particle(
        ThinSliceQuadrupoleExitData el,
        LocalParticle* part0
) {

    track_magnet_particles(
        /*weight*/                0., // unused
        /*part0*/                 part0,
        /*length*/                ThinSliceQuadrupoleExitData_get__parent_length(el),
        /*order*/                 ThinSliceQuadrupoleExitData_get__parent_order(el),
        /*inv_factorial_order*/   ThinSliceQuadrupoleExitData_get__parent_inv_factorial_order(el),
        /*knl*/                   ThinSliceQuadrupoleExitData_getp1__parent_knl(el, 0),
        /*ksl*/                   ThinSliceQuadrupoleExitData_getp1__parent_ksl(el, 0),
        /*num_multipole_kicks*/   0, // unused
        /*model*/                 0, // unused
        /*default_model*/         QUADRUPOLE_DEFAULT_MODEL,
        /*integrator*/            0, // unused
        /*default_integrator*/    QUADRUPOLE_DEFAULT_INTEGRATOR,
        /*radiation_flag*/        ThinSliceQuadrupoleExitData_get_radiation_flag(el),
        /*radiation_flag_parent*/ ThinSliceQuadrupoleExitData_get__parent_radiation_flag(el),
        /*radiation_record*/      NULL,
        /*delta_taper*/           ThinSliceQuadrupoleExitData_get_delta_taper(el),
        /*h*/                     0.,
        /*hxl*/                   0.,
        /*k0*/                    0.,
        /*k1*/                    ThinSliceQuadrupoleExitData_get__parent_k1(el),
        /*k2*/                    0.,
        /*k3*/                    0.,
        /*k0s*/                   0.,
        /*k1s*/                   ThinSliceQuadrupoleExitData_get__parent_k1s(el),
        /*k2s*/                   0.,
        /*k3s*/                   0.,
        /*ks*/                    0.,
        /*dks_ds*/                0.,
        /*rbend_model*/           -1, // not rbend
        /*rbend_shift*/           0.,
        /*body_active*/           0, // disabled
        /*edge_entry_active*/     0,
        /*edge_exit_active*/      ThinSliceQuadrupoleExitData_get__parent_edge_exit_active(el),
        /*edge_entry_model*/      0,
        /*edge_exit_model*/       1,
        /*edge_entry_angle*/      0.,
        /*edge_exit_angle*/       0.,
        /*edge_entry_angle_fdown*/0.,
        /*edge_exit_angle_fdown*/ 0.,
        /*edge_entry_fint*/       0.,
        /*edge_exit_fint*/        0.,
        /*edge_entry_hgap*/       0.,
        /*edge_exit_hgap*/        0.
    );
}

#endif // XTRACK_EXIT_SLICE_QUADRUPOLE_H