// This file is generated by _generate_slice_elements_c_code.py
// Do not edit it directly.

// copyright ############################### //
// This file is part of the Xtrack Package.  //
// Copyright (c) CERN, 2021.                 //
// ######################################### //

#ifndef XTRACK_THIN_SLICE_CAVITY_H
#define XTRACK_THIN_SLICE_CAVITY_H

#include <beam_elements/elements_src/track_rf.h>

GPUFUN
void ThinSliceCavity_track_local_particle(ThinSliceCavityData el, LocalParticle* part0)
{
    track_rf_particles(
        /*weight*/                ThinSliceCavityData_get_weight(el),
        /*part0*/                 part0,
        /*length*/                ThinSliceCavityData_get__parent_length(el),
        /*voltage*/               ThinSliceCavityData_get__parent_voltage(el),
        /*frequency*/             ThinSliceCavityData_get__parent_frequency(el),
        /*lag*/                   ThinSliceCavityData_get__parent_lag(el),
        /*transverse_voltage*/    0.,
        /*transverse_lag*/        0.,
        /*absolute_time*/         ThinSliceCavityData_get__parent_absolute_time(el),
        /*order*/                 -1, // not used here
        /*knl*/                   NULL,
        /*ksl*/                   NULL,
        /*pn*/                    NULL,
        /*ps*/                    NULL,
        /*num_kicks*/             1, // kick only
        /*model*/                 -1, // kick only
        /*default_model*/         6, // drift-kick-drift-expanded
        /*integrator*/            3, // uniform
        /*default_integrator*/    3, // Uniform
        /*radiation_flag*/        0, // not used here
        /*radiation_flag_parent*/ 0, // not used here
        /*lag_taper*/             ThinSliceCavityData_get__parent_lag_taper(el),
        /*body_active*/           1,
        /*edge_entry_active*/     0, // not used here
        /*edge_exit_active*/      0  // not used here
    );

}

#endif  // XTRACK_THIN_SLICE_CAVITY_H