// This file is generated by _generate_slice_elements_c_code.py
// Do not edit it directly.

// copyright ############################### //
// This file is part of the Xtrack Package.  //
// Copyright (c) CERN, 2023.                 //
// ######################################### //

#ifndef XTRACK_THIN_SLICE_OCTUPOLE_H
#define XTRACK_THIN_SLICE_OCTUPOLE_H

#include <headers/track.h>
#include <beam_elements/elements_src/track_magnet.h>
#include <beam_elements/elements_src/default_magnet_config.h>

GPUFUN
void ThinSliceOctupole_track_local_particle(
        ThinSliceOctupoleData el,
        LocalParticle* part0
) {

    track_magnet_particles(
        /*weight*/                ThinSliceOctupoleData_get_weight(el),
        /*part0*/                 part0,
        /*length*/                ThinSliceOctupoleData_get__parent_length(el),
        /*order*/                 ThinSliceOctupoleData_get__parent_order(el),
        /*inv_factorial_order*/   ThinSliceOctupoleData_get__parent_inv_factorial_order(el),
        /*knl*/                   ThinSliceOctupoleData_getp1__parent_knl(el, 0),
        /*ksl*/                   ThinSliceOctupoleData_getp1__parent_ksl(el, 0),
        /*num_multipole_kicks*/   1, // kick only
        /*model*/                 -1, // kick only
        /*default_model*/         OCTUPOLE_DEFAULT_MODEL,
        /*integrator*/            3, // uniform
        /*default_integrator*/    OCTUPOLE_DEFAULT_INTEGRATOR,
        /*radiation_flag*/        ThinSliceOctupoleData_get_radiation_flag(el),
        /*radiation_flag_parent*/ ThinSliceOctupoleData_get__parent_radiation_flag(el),
        /*radiation_record*/      NULL,
        /*delta_taper*/           ThinSliceOctupoleData_get_delta_taper(el),
        /*h*/                     0.,
        /*hxl*/                   0.,
        /*k0*/                    0.,
        /*k1*/                    0.,
        /*k2*/                    0.,
        /*k3*/                    ThinSliceOctupoleData_get__parent_k3(el),
        /*k0s*/                   0.,
        /*k1s*/                   0.,
        /*k2s*/                   0.,
        /*k3s*/                   ThinSliceOctupoleData_get__parent_k3s(el),
        /*ks*/                    0.,
        /*dks_ds*/                0.,
        /*rbend_model*/           -1, // not rbend
        /*rbend_shift*/           0.,
        /*body_active*/           1,
        /*edge_entry_active*/     0,
        /*edge_exit_active*/      0,
        /*edge_entry_model*/      0,
        /*edge_exit_model*/       0,
        /*edge_entry_angle*/      0.,
        /*edge_exit_angle*/       0.,
        /*edge_entry_angle_fdown*/0.,
        /*edge_exit_angle_fdown*/ 0.,
        /*edge_entry_fint*/       0.,
        /*edge_exit_fint*/        0.,
        /*edge_entry_hgap*/       0.,
        /*edge_exit_hgap*/        0.
    );
}

#endif // XTRACK_THIN_SLICE_OCTUPOLE_H