// This file is generated by _generate_slice_elements_c_code.py
// Do not edit it directly.

// copyright ############################### //
// This file is part of the Xtrack Package.  //
// Copyright (c) CERN, 2023.                 //
// ######################################### //

#ifndef XTRACK_THIN_SLICE_BEND_H
#define XTRACK_THIN_SLICE_BEND_H

#include <headers/track.h>
#include <beam_elements/elements_src/track_magnet.h>
#include <beam_elements/elements_src/default_magnet_config.h>

GPUFUN
void ThinSliceBend_track_local_particle(
        ThinSliceBendData el,
        LocalParticle* part0
) {

    track_magnet_particles(
        /*weight*/                ThinSliceBendData_get_weight(el),
        /*part0*/                 part0,
        /*length*/                ThinSliceBendData_get__parent_length(el),
        /*order*/                 ThinSliceBendData_get__parent_order(el),
        /*inv_factorial_order*/   ThinSliceBendData_get__parent_inv_factorial_order(el),
        /*knl*/                   ThinSliceBendData_getp1__parent_knl(el, 0),
        /*ksl*/                   ThinSliceBendData_getp1__parent_ksl(el, 0),
        /*num_multipole_kicks*/   1, // kick only
        /*model*/                 -1, // kick only
        /*default_model*/         BEND_DEFAULT_MODEL,
        /*integrator*/            3, // uniform
        /*default_integrator*/    BEND_DEFAULT_INTEGRATOR,
        /*radiation_flag*/        ThinSliceBendData_get_radiation_flag(el),
        /*radiation_flag_parent*/ ThinSliceBendData_get__parent_radiation_flag(el),
        /*radiation_record*/      NULL,
        /*delta_taper*/           ThinSliceBendData_get_delta_taper(el),
        /*h*/                     ThinSliceBendData_get__parent_h(el),
        /*hxl*/                   0.,
        /*k0*/                    ThinSliceBendData_get__parent_k0(el),
        /*k1*/                    ThinSliceBendData_get__parent_k1(el),
        /*k2*/                    0.,
        /*k3*/                    0.,
        /*k0s*/                   0.,
        /*k1s*/                   0.,
        /*k2s*/                   0.,
        /*k3s*/                   0.,
        /*ks*/                    0.,
        /*dks_ds*/                0.,
        /*rbend_model*/           -1, // not rbend
        /*rbend_shift*/           0.,
        /*body_active*/           1,
        /*edge_entry_active*/     0,
        /*edge_exit_active*/      0,
        /*edge_entry_model*/      0,
        /*edge_exit_model*/       0,
        /*edge_entry_angle*/      0,
        /*edge_exit_angle*/       0,
        /*edge_entry_angle_fdown*/0,
        /*edge_exit_angle_fdown*/ 0,
        /*edge_entry_fint*/       0,
        /*edge_exit_fint*/        0,
        /*edge_entry_hgap*/       0,
        /*edge_exit_hgap*/        0
    );

}

#endif // XTRACK_TRUEBEND_H