# copyright ############################### #
# This file is part of the Xtrack Package.  #
# Copyright (c) CERN, 2026.                 #
# ######################################### #

"""Rest energies m*c**2 in eV (mass parameters in eV/c**2).

All isotope masses are for fully stripped ground-state nuclei.
U_MASS_EV is the atomic mass unit, defined from the NEUTRAL carbon-12 atom.

Generated by test_data/particle_masses/generate_masses.py. See
test_data/particle_masses/README.md and the source excerpts there for provenance,
calculations and approximations.
Regenerate from the repository root:
    python test_data/particle_masses/generate_masses.py

Sources:
  AME2020: https://doi.org/10.1088/1674-1137/abddaf (Eq. 1)
  CODATA 2022: https://physics.nist.gov/cuu/Constants/Table/allascii.txt
  NIST ASD 5.12: https://doi.org/10.18434/T4W30F (total electron binding energies)
  PDG 2024: https://pdg.lbl.gov/2024/listings/particle_properties.html

Conversion: M_nucleus*c**2 = M_atom[u]*U_MASS_EV - Z*ELECTRON_MASS_EV + B_e.
B_e is positive and includes ALL electrons. The same NIST elemental B_e is
used for all isotopes; isotope shifts of B_e are neglected. The listed sigma
is an approximate quadrature of input uncertainties, ignoring correlations
and the unquantified isotope-shift error (not a certified total uncertainty).
AME '#' marks extrapolated atomic masses. Decimal places are computational
guard digits, not a claim of experimental accuracy. Converted isotope masses
are rounded to 0.1 eV; direct CODATA values retain their published precision.
"""

# Direct CODATA 2022 values; no electron subtraction for these bare nuclei.
ELECTRON_MASS_EV  =       510998.95069  # CODATA 2022; sigma = 0.00016 eV
MUON_MASS_EV      =        105658375.5  # CODATA 2022; sigma = 2.3 eV
PROTON_MASS_EV    =       938272089.43  # CODATA 2022; sigma = 0.29 eV
DEUTERON_MASS_EV  =       1875612945.0  # CODATA 2022; sigma = 0.58 eV
TRITON_MASS_EV    =      2808921136.68  # CODATA 2022; sigma = 0.88 eV
He3_MASS_EV       =      2808391611.12  # CODATA 2022; sigma = 0.88 eV
He4_MASS_EV       =       3727379411.8  # CODATA 2022; sigma = 1.2 eV
NEUTRON_MASS_EV   =       939565421.94  # CODATA 2022; sigma = 0.48 eV
U_MASS_EV         =       931494103.72  # CODATA 2022; sigma = 0.29 eV

# Meson values retained from the previous table (PDG 2024); photon is exact.
PHOTON_MASS_EV    =            0.0
PION_MASS_EV      =    139570390.0  # sigma = 180 eV
KAON_MASS_EV      =    493677000.0  # sigma = 15000 eV
PION0_MASS_EV     =    134976800.0  # sigma = 500 eV
KAON0_MASS_EV     =    497611000.0  # sigma = 13000 eV

# C: Z = 6; NIST ASD B_e = 1030.1085 eV; sigma(B_e) = 0.0004 eV.
C10_MASS_EV       =       9327574745.9  # AME atom: 10.016853217 u; approx sigma = 70 eV
C11_MASS_EV       =      10254019574.0  # AME atom: 11.011432597 u; approx sigma = 60 eV
C12_MASS_EV       =      11174864281.0  # AME atom: 12.0 u; approx sigma = 3.5 eV
C13_MASS_EV       =      12109483394.1  # AME atom: 13.00335483534 u; approx sigma = 3.8 eV
C14_MASS_EV       =      13040872381.8  # AME atom: 14.00324198862 u; approx sigma = 5.5 eV
C15_MASS_EV       =      13979219736.7  # AME atom: 15.010599256 u; approx sigma = 8e+02 eV

# O: Z = 8; NIST ASD B_e = 2043.8429 eV; sigma(B_e) = 0.0022 eV.
O14_MASS_EV       =      13044839285.3  # AME atom: 14.008596706 u; approx sigma = 25 eV
O15_MASS_EV       =      13971181229.9  # AME atom: 15.003065636 u; approx sigma = 4.9e+02 eV
O16_MASS_EV       =      14895082709.6  # AME atom: 15.99491461926 u; approx sigma = 4.6 eV
O17_MASS_EV       =      15830505051.3  # AME atom: 16.99913175595 u; approx sigma = 5 eV
O18_MASS_EV       =      16762025102.9  # AME atom: 17.99915961214 u; approx sigma = 5.3 eV
O19_MASS_EV       =      17697634879.9  # AME atom: 19.003577969 u; approx sigma = 2.6e+03 eV
O20_MASS_EV       =      18629592297.7  # AME atom: 20.004075357 u; approx sigma = 8.8e+02 eV

# Ne: Z = 10; NIST ASD B_e = 3511.696 eV; sigma(B_e) = 0.019 eV.
Ne19_MASS_EV      =      17695033545.7  # AME atom: 19.001880906 u; approx sigma = 1.6e+02 eV
Ne20_MASS_EV      =      18617733664.4  # AME atom: 19.99244017525 u; approx sigma = 6 eV
Ne21_MASS_EV      =      19550537923.7  # AME atom: 20.993846685 u; approx sigma = 39 eV
Ne22_MASS_EV      =      20479739087.6  # AME atom: 21.991385113 u; approx sigma = 18 eV
Ne23_MASS_EV      =      21414103862.4  # AME atom: 22.994466905 u; approx sigma = 1e+02 eV
Ne24_MASS_EV      =      22344800368.7  # AME atom: 23.993610649 u; approx sigma = 5.1e+02 eV

# Ar: Z = 18; NIST ASD B_e = 14400.8 eV; sigma(B_e) = 2.4 eV.
Ar35_MASS_EV      =      32570062761.0  # AME atom: 34.975257719 u; approx sigma = 6.8e+02 eV
Ar36_MASS_EV      =      33494372611.2  # AME atom: 35.967545106 u; approx sigma = 28 eV
Ar37_MASS_EV      =      34425150577.6  # AME atom: 36.966776301 u; approx sigma = 2.1e+02 eV
Ar38_MASS_EV      =      35352877533.8  # AME atom: 37.962732102 u; approx sigma = 2e+02 eV
Ar39_MASS_EV      =      36285844269.2  # AME atom: 38.964313037 u; approx sigma = 5e+03 eV
Ar40_MASS_EV      =      37215540668.5  # AME atom: 39.96238312204 u; approx sigma = 12 eV
Ar41_MASS_EV      =      38149007162.5  # AME atom: 40.96450057 u; approx sigma = 3.5e+02 eV
Ar42_MASS_EV      =      39079146097.8  # AME atom: 41.963045737 u; approx sigma = 5.8e+03 eV
Ar43_MASS_EV      =      40013053068.4  # AME atom: 42.965636056 u; approx sigma = 5.3e+03 eV
Ar44_MASS_EV      =      40943883722.9  # AME atom: 43.964923814 u; approx sigma = 1.6e+03 eV
Ar45_MASS_EV      =      41878280285.0  # AME atom: 44.968039731 u; approx sigma = 5.1e+02 eV
Ar46_MASS_EV      =      42809773935.0  # AME atom: 45.968039244 u; approx sigma = 2.3e+03 eV
Ar47_MASS_EV      =      43745672019.9  # AME atom: 46.972767112 u; approx sigma = 1.2e+03 eV

# Fe: Z = 26; NIST ASD B_e = 34619 eV; sigma(B_e) = 11 eV.
Fe52_MASS_EV      =      48376109944.2  # AME atom: 51.948113364 u; approx sigma = 1.8e+02 eV
Fe53_MASS_EV      =      49304988659.3  # AME atom: 52.945305629 u; approx sigma = 1.7e+03 eV
Fe54_MASS_EV      =      50231175631.3  # AME atom: 53.939608189 u; approx sigma = 3.4e+02 eV
Fe55_MASS_EV      =      51161442928.4  # AME atom: 54.938291158 u; approx sigma = 3.1e+02 eV
Fe56_MASS_EV      =      52089811291.0  # AME atom: 55.934935537 u; approx sigma = 2.7e+02 eV
Fe57_MASS_EV      =      53021730540.7  # AME atom: 56.93539195 u; approx sigma = 2.7e+02 eV
Fe58_MASS_EV      =      53951251390.6  # AME atom: 57.933273575 u; approx sigma = 3.2e+02 eV
Fe59_MASS_EV      =      54884235807.6  # AME atom: 58.934873492 u; approx sigma = 3.3e+02 eV
Fe60_MASS_EV      =      55814981695.2  # AME atom: 59.934070249 u; approx sigma = 3.4e+03 eV
Fe61_MASS_EV      =      56748968469.7  # AME atom: 60.936746241 u; approx sigma = 2.6e+03 eV
Fe62_MASS_EV      =      57680505019.7  # AME atom: 61.936791809 u; approx sigma = 2.8e+03 eV
Fe63_MASS_EV      =      58615241551.0  # AME atom: 62.940272698 u; approx sigma = 4.3e+03 eV
Fe64_MASS_EV      =      59547401731.7  # AME atom: 63.940987761 u; approx sigma = 5e+03 eV

# Xe: Z = 54; NIST ASD B_e = 202400 eV; sigma(B_e) = 140 eV.
Xe112_MASS_EV     =     104239921725.1  # AME atom: 111.935559068 u; approx sigma = 8.3e+03 eV
Xe113_MASS_EV     =     105169238549.9  # AME atom: 112.933221663 u; approx sigma = 6.8e+03 eV
Xe114_MASS_EV     =     106095850381.9  # AME atom: 113.927980329 u; approx sigma = 1.1e+04 eV
Xe115_MASS_EV     =     107025773627.0  # AME atom: 114.926293943 u; approx sigma = 1.2e+04 eV
Xe116_MASS_EV     =     107952877610.1  # AME atom: 115.921580955 u; approx sigma = 1.3e+04 eV
Xe117_MASS_EV     =     108883233244.6  # AME atom: 116.920358758 u; approx sigma = 1e+04 eV
Xe118_MASS_EV     =     109810833628.4  # AME atom: 117.916178678 u; approx sigma = 1e+04 eV
Xe119_MASS_EV     =     110741612310.2  # AME atom: 118.915410641 u; approx sigma = 1e+04 eV
Xe120_MASS_EV     =     111669728467.9  # AME atom: 119.911784267 u; approx sigma = 1.2e+04 eV
Xe121_MASS_EV     =     112600914009.6  # AME atom: 120.911453012 u; approx sigma = 1e+04 eV
Xe122_MASS_EV     =     113529534121.4  # AME atom: 121.908367655 u; approx sigma = 1.1e+04 eV
Xe123_MASS_EV     =     114461134955.7  # AME atom: 122.908482235 u; approx sigma = 9.5e+03 eV
Xe124_MASS_EV     =     115390209912.5  # AME atom: 123.905885174 u; approx sigma = 1.4e+03 eV
Xe125_MASS_EV     =     116322172060.3  # AME atom: 124.90638764 u; approx sigma = 1.4e+03 eV
Xe126_MASS_EV     =     117251719138.3  # AME atom: 125.904297422 u; approx sigma = 1.4e+02 eV
Xe127_MASS_EV     =     118184038745.1  # AME atom: 126.905183636 u; approx sigma = 4.1e+03 eV
Xe128_MASS_EV     =     119113993198.4  # AME atom: 127.90353075341 u; approx sigma = 1.4e+02 eV
Xe129_MASS_EV     =     120046651766.7  # AME atom: 128.90478085742 u; approx sigma = 1.4e+02 eV
Xe130_MASS_EV     =     120976961465.0  # AME atom: 129.903509346 u; approx sigma = 1.5e+02 eV
Xe131_MASS_EV     =     121909922468.9  # AME atom: 130.90508412808 u; approx sigma = 1.5e+02 eV
Xe132_MASS_EV     =     122840551173.1  # AME atom: 131.90415508346 u; approx sigma = 1.5e+02 eV
Xe133_MASS_EV     =     123773680668.0  # AME atom: 132.905910748 u; approx sigma = 2.4e+03 eV
Xe134_MASS_EV     =     124704692520.4  # AME atom: 133.90539303 u; approx sigma = 1.5e+02 eV
Xe135_MASS_EV     =     125637899093.1  # AME atom: 134.907231441 u; approx sigma = 3.7e+03 eV
Xe136_MASS_EV     =     126569377392.2  # AME atom: 135.907214474 u; approx sigma = 1.5e+02 eV
Xe137_MASS_EV     =     127504917251.5  # AME atom: 136.911557771 u; approx sigma = 1.8e+02 eV
Xe138_MASS_EV     =     128438822524.9  # AME atom: 137.914146268 u; approx sigma = 2.8e+03 eV
Xe139_MASS_EV     =     129374644286.9  # AME atom: 138.9187922 u; approx sigma = 2.1e+03 eV
Xe140_MASS_EV     =     130308796515.2  # AME atom: 139.921645814 u; approx sigma = 2.3e+03 eV
Xe141_MASS_EV     =     131245079772.0  # AME atom: 140.926787181 u; approx sigma = 2.9e+03 eV
Xe142_MASS_EV     =     132179541535.8  # AME atom: 141.929973095 u; approx sigma = 2.7e+03 eV

# Au: Z = 79; NIST ASD B_e = 517100 eV; sigma(B_e) = 1100 eV.
Au176_MASS_EV     =     163884589470.5  # AME atom: 175.980116925 u; approx sigma = 3.3e+04 eV
Au177_MASS_EV     =     164813058804.2  # AME atom: 176.976869701 u; approx sigma = 1e+04 eV
Au178_MASS_EV     =     165743795615.3  # AME atom: 177.976056714 u; approx sigma = 1e+04 eV
Au179_MASS_EV     =     166672604176.8  # AME atom: 178.973173666 u; approx sigma = 1.2e+04 eV
Au180_MASS_EV     =     167603461205.7  # AME atom: 179.972489738 u; approx sigma = 4.9e+03 eV
Au181_MASS_EV     =     168532709816.2  # AME atom: 180.970079102 u; approx sigma = 2e+04 eV
Au182_MASS_EV     =     169463771083.4  # AME atom: 181.969614433 u; approx sigma = 1.9e+04 eV
Au183_MASS_EV     =     170393377675.5  # AME atom: 182.967588106 u; approx sigma = 9.5e+03 eV
Au184_MASS_EV     =     171324744553.0  # AME atom: 183.967451523 u; approx sigma = 2.2e+04 eV
Au185_MASS_EV     =     172254699221.1  # AME atom: 184.965798871 u; approx sigma = 2.8e+03 eV
Au186_MASS_EV     =     173186336618.4  # AME atom: 185.965952703 u; approx sigma = 2.1e+04 eV
Au187_MASS_EV     =     174116516797.5  # AME atom: 186.964542147 u; approx sigma = 2.3e+04 eV
Au188_MASS_EV     =     175048668367.5  # AME atom: 187.965247966 u; approx sigma = 2.9e+03 eV
Au189_MASS_EV     =     175978951827.0  # AME atom: 188.963948286 u; approx sigma = 2e+04 eV
Au190_MASS_EV     =     176911194348.9  # AME atom: 189.964751746 u; approx sigma = 3.6e+03 eV
Au191_MASS_EV     =     177841724082.4  # AME atom: 190.963716452 u; approx sigma = 5e+03 eV
Au192_MASS_EV     =     178774243913.0  # AME atom: 191.964817615 u; approx sigma = 1.6e+04 eV
Au193_MASS_EV     =     179705105371.0  # AME atom: 192.964138442 u; approx sigma = 8.7e+03 eV
Au194_MASS_EV     =     180637792354.5  # AME atom: 193.965419051 u; approx sigma = 2.4e+03 eV
Au195_MASS_EV     =     181568931346.6  # AME atom: 194.965037823 u; approx sigma = 1.6e+03 eV
Au196_MASS_EV     =     182501853794.0  # AME atom: 195.966571213 u; approx sigma = 3.2e+03 eV
Au197_MASS_EV     =     183433346863.8  # AME atom: 196.966570103 u; approx sigma = 1.2e+03 eV
Au198_MASS_EV     =     184366399926.3  # AME atom: 197.968243714 u; approx sigma = 1.2e+03 eV
Au199_MASS_EV     =     185298381070.1  # AME atom: 198.968766573 u; approx sigma = 1.2e+03 eV
Au200_MASS_EV     =     186231728833.1  # AME atom: 199.970756558 u; approx sigma = 2.7e+04 eV
Au201_MASS_EV     =     187164062324.8  # AME atom: 200.971657678 u; approx sigma = 3.4e+03 eV
Au202_MASS_EV     =     188097604152.5  # AME atom: 201.973856 u; approx sigma = 2.3e+04 eV
Au203_MASS_EV     =     189030307793.8  # AME atom: 202.975154492 u; approx sigma = 3.3e+03 eV
Au204_MASS_EV     =     189964554935.8  # AME atom: 203.97811 u #; approx sigma = 2e+05 eV
Au205_MASS_EV     =     190897869179.0  # AME atom: 204.980064 u #; approx sigma = 2e+05 eV
Au206_MASS_EV     =     191833743168.0  # AME atom: 205.984766 u #; approx sigma = 3e+05 eV
Au207_MASS_EV     =     192768787195.8  # AME atom: 206.988577 u #; approx sigma = 3e+05 eV
Au208_MASS_EV     =     193705011426.6  # AME atom: 207.993655 u #; approx sigma = 3e+05 eV
Au209_MASS_EV     =     194640185863.5  # AME atom: 208.997606 u #; approx sigma = 4e+05 eV
Au210_MASS_EV     =     195576589872.6  # AME atom: 210.002877 u #; approx sigma = 4e+05 eV

# Pb: Z = 82; NIST ASD B_e = 568200 eV; sigma(B_e) = 1500 eV.
Pb185_MASS_EV     =     172273534262.3  # AME atom: 184.98761 u; approx sigma = 1.6e+04 eV
Pb186_MASS_EV     =     173201888680.4  # AME atom: 185.984239409 u; approx sigma = 1.1e+04 eV
Pb187_MASS_EV     =     174133076725.9  # AME atom: 186.983910842 u; approx sigma = 5.3e+03 eV
Pb188_MASS_EV     =     175061746760.2  # AME atom: 187.980879079 u; approx sigma = 1e+04 eV
Pb189_MASS_EV     =     175993207869.5  # AME atom: 188.980843658 u; approx sigma = 1.4e+04 eV
Pb190_MASS_EV     =     176922129385.8  # AME atom: 189.978081872 u; approx sigma = 1.3e+04 eV
Pb191_MASS_EV     =     177853748852.8  # AME atom: 190.978216455 u; approx sigma = 6.8e+03 eV
Pb192_MASS_EV     =     178782982353.6  # AME atom: 191.975789598 u; approx sigma = 5.9e+03 eV
Pb193_MASS_EV     =     179714799048.6  # AME atom: 192.976135914 u; approx sigma = 1e+04 eV
Pb194_MASS_EV     =     180644314541.5  # AME atom: 193.974011788 u; approx sigma = 1.7e+04 eV
Pb195_MASS_EV     =     181576278471.3  # AME atom: 194.974516167 u; approx sigma = 5.3e+03 eV
Pb196_MASS_EV     =     182506162380.3  # AME atom: 195.972787552 u; approx sigma = 7.9e+03 eV
Pb197_MASS_EV     =     183438259333.0  # AME atom: 196.973434737 u; approx sigma = 5e+03 eV
Pb198_MASS_EV     =     184368431379.3  # AME atom: 197.97201545 u; approx sigma = 8.9e+03 eV
Pb199_MASS_EV     =     185300761191.6  # AME atom: 198.97291262 u; approx sigma = 7e+03 eV
Pb200_MASS_EV     =     186231236171.8  # AME atom: 199.971818546 u; approx sigma = 1e+04 eV
Pb201_MASS_EV     =     187163710100.2  # AME atom: 200.972870431 u; approx sigma = 1.4e+04 eV
Pb202_MASS_EV     =     188094534629.2  # AME atom: 201.972151613 u; approx sigma = 4.1e+03 eV
Pb203_MASS_EV     =     189027182857.8  # AME atom: 202.973390617 u; approx sigma = 6.7e+03 eV
Pb204_MASS_EV     =     189958353629.7  # AME atom: 203.973043506 u; approx sigma = 1.9e+03 eV
Pb205_MASS_EV     =     190891187385.9  # AME atom: 204.974481682 u; approx sigma = 1.9e+03 eV
Pb206_MASS_EV     =     191822666146.0  # AME atom: 205.97446521 u; approx sigma = 1.9e+03 eV
Pb207_MASS_EV     =     192755493787.0  # AME atom: 206.975896821 u; approx sigma = 1.9e+03 eV
Pb208_MASS_EV     =     193687691340.1  # AME atom: 207.976652005 u; approx sigma = 1.9e+03 eV
Pb209_MASS_EV     =     194623319389.5  # AME atom: 208.981089978 u; approx sigma = 2.3e+03 eV
Pb210_MASS_EV     =     195557699637.4  # AME atom: 209.984188381 u; approx sigma = 2.1e+03 eV
Pb211_MASS_EV     =     196493429158.2  # AME atom: 210.988735288 u; approx sigma = 2.7e+03 eV
Pb212_MASS_EV     =     197427867344.9  # AME atom: 211.991895891 u; approx sigma = 2.4e+03 eV
Pb213_MASS_EV     =     198363706780.2  # AME atom: 212.996560796 u; approx sigma = 7.1e+03 eV
Pb214_MASS_EV     =     199298221463.1  # AME atom: 213.999803521 u; approx sigma = 2.5e+03 eV
Pb215_MASS_EV     =     200234240830.4  # AME atom: 215.004661591 u; approx sigma = 5.3e+04 eV
Pb216_MASS_EV     =     201168902395.0  # AME atom: 216.008062 u #; approx sigma = 2e+05 eV
Pb217_MASS_EV     =     202105147118.7  # AME atom: 217.013162 u #; approx sigma = 3e+05 eV
Pb218_MASS_EV     =     203040010436.6  # AME atom: 218.016779 u #; approx sigma = 3e+05 eV
Pb219_MASS_EV     =     203976494554.2  # AME atom: 219.022136 u #; approx sigma = 4e+05 eV
Pb220_MASS_EV     =     204911499459.2  # AME atom: 220.025905 u #; approx sigma = 4e+05 eV
