"""TPSA module to enable tracking for Xtrack elements with TPSA's using the ``xgtpsa`` package.

The TPSA algebra itself comes from the standalone ``xgtpsa`` package (which owns the GTPSA engine).
Everything here is related to tracking with TPSAs: element bridge sources (``c_src/``,
generated by ``gen_bridge.py``, compiled on demand by ``_bridge_build``), map
(``ParticlesTpsa``), knobs, monitors and optics. CPU only.

    import xtrack as xt
    import xtrack.tpsa as xtpsa
    el = xt.DriftExact(length=2.5)

    # TPSA map: track the element's own physics through it
    m = xtpsa.ParticlesTpsa(order=3, x=1e-4, px=1.5e-4, y=-1e-4, py=1e-4,
                            zeta=1e-3, delta=2e-3, p0c=7e12)
    el.track(m)                        # m.const_part (orbit), m.jacobian() (first-order)

    # equivalent call with float: same C source compiled with doubles
    p = xt.Particles(x=1e-4, px=1.5e-4, y=-1e-4, py=1e-4, zeta=1e-3, delta=2e-3, p0c=7e12)
    xtpsa.track_num_twin(el, p)        # same as native line.track
"""

from __future__ import annotations

try:
    import xgtpsa  # the GTPSA engine, import it early for a clear error
except ImportError as exc:
    raise ImportError(
        "xtrack.tpsa needs the xgtpsa package (the GTPSA engine): "
        "pip install -e <gtpsa_lib> and run its build.sh"
    ) from exc

from .particles import ParticlesTpsa
from .knobs import Knobs
from .track import track_num_twin
from .backend import GtpsaBackend
from ._tpsa_monitor import TpsaMonitor
from .optics import TpsaOptics
from xtrack.tracking_backends import register_tracking_backend

register_tracking_backend(ParticlesTpsa, GtpsaBackend())

__all__ = ["ParticlesTpsa", "Knobs", "TpsaMonitor", "TpsaOptics",
           "track_num_twin", "GtpsaBackend"]
