# AUTO-GENERATED by gtpsa_lib/gen_bridge.py -- do not edit.
CDEF = r"""
    void* mad_desc_newv(int nv, unsigned char mo);
    int   mad_desc_getnv(const void* d, unsigned char* mo_, int* np_, unsigned char* po_);
    void* mad_tpsa_newd(void* desc, unsigned char mo);
    const void* mad_tpsa_desc(const void* t);
    unsigned char mad_tpsa_ord(const void* t, _Bool hi);
    void  mad_tpsa_del(void* t);
    void  mad_tpsa_setvar(void* t, double v, int iv, double scl);
    void  mad_tpsa_setval(void* t, double v);
    double mad_tpsa_geti(void* t, int i);
    double mad_tpsa_getm(void* t, int n, const unsigned char* m);
    int    mad_tpsa_cycle(void* t, int i, int n, unsigned char* m, double* v);
"""
