"""cffi ABI binding to the standalone GTPSA core library (libgtpsa_core.so).

Descriptor and Tpsa reach the mad_* functions through cffi ABI mode (``ffi.dlopen``) against the
prebuilt shared object. The core is built externally (gtpsa_lib/build.sh) and
located via the ``XTRACK_GTPSA_LIB`` env var (which points at a file in the gtpsa_lib
dir). Loading is lazy: importing ``xtrack.tpsa`` does not fail, but tracking does.

The element/line tracking functions live in the two xobjects-compiled modules
(``bridge_lib``).  Both those modules and Descriptor/Tpsa link the same shared object file,
so the map's ``tpsa_t`` handles share mad's global descriptor state.

TPSA handles are opaque cffi ``void*``. C conventions: ``setvar`` variable indices start
from 1, not 0! ``mad_tpsa_dflt = 255`` is the full descriptor order.
"""

from __future__ import annotations

import os
import json
import hashlib
import subprocess
from typing import TYPE_CHECKING, Any, Callable, Iterable, Sequence

import cffi
import numpy as np

from ._generated_cdef import CDEF

if TYPE_CHECKING:
    # xobjects does not import context_cpu eagerly (it pulls in the compiler path),
    # so these are named for readers/checkers only; bridge_lib imports them at call time.
    from xobjects.context import Kernel
    from xobjects.context_cpu import ContextCpu, KernelCpu

_DFLT = 255  # full descriptor order (mad_tpsa_dflt)

# The cffi cdef (mad_tpsa_* functions) is generated by gtpsa_lib/gen_bridge.py.
# The bridge entry points are not here, but in the
# xobjects-compiled flavor modules, whose cdef is supplied at build time
# (``_bridge_entry_cdef``).
_ffi = cffi.FFI()
_ffi.cdef(CDEF)
_lib: Any = None  # the dlopened libgtpsa_core.so; its mad_* members come from the cdef


def _default_so_path() -> str | None:
    return os.environ.get("XTRACK_GTPSA_LIB")


def lib() -> Any:
    """Dlopen ``libgtpsa_core.so`` (the mad_* functions), throw a clear error if missing.

    The core is number-agnostic (mad_* + LAPACK/BLAS, no bridge). Descriptor/Tpsa run
    off it, and the same file is linked by the xobjects bridge modules so the map's
    ``tpsa_t`` handles share mad's global descriptor state.
    """
    global _lib
    if _lib is None:
        core = _core_so()
        if not os.path.exists(core):
            raise RuntimeError(
                f"libgtpsa_core.so not found (got {core!r}); build it (gtpsa_lib/build.sh) "
                "and point XTRACK_GTPSA_LIB at a file in that gtpsa_lib directory."
            )
        _lib = _ffi.dlopen(core)
    return _lib


def ffi() -> cffi.FFI:
    return _ffi


# --- xobjects-compiled bridge --------------------------------------- #
#
# The ``xt_bridge.cpp`` translation unit compiled per type through ``ContextCpu.build_kernels``
# (C++, linking the shared object), yielding two cffi API-mode modules, which are track functions.
# The built ``.so`` is cached on disk keyed by (registry, flavor, xtrack rev): a matching one is
# re-imported without recompiling; a stale key rebuilds.
_BRIDGE_FLAVORS = ("num", "tpsa")
_bridge_modules: dict[str, dict[str, KernelCpu]] = {}  # flavor -> kernels
_bridge_ctx: ContextCpu | None = None


def _gtpsa_dir() -> str:
    """The gtpsa_lib source dir (holds xt_bridge.cpp + the core .so), from XTRACK_GTPSA_LIB."""
    p = _default_so_path()
    if not p:
        raise RuntimeError(
            "XTRACK_GTPSA_LIB is not set; cannot locate the gtpsa_lib sources."
        )
    return os.path.dirname(os.path.abspath(p))


def _core_so() -> str:
    return os.path.join(_gtpsa_dir(), "libgtpsa_core.so")


def _xtrack_rev() -> str:
    try:
        import xtrack

        root = os.path.dirname(os.path.dirname(os.path.abspath(xtrack.__file__)))
        return (
            subprocess.check_output(
                ["git", "-C", root, "rev-parse", "HEAD"], stderr=subprocess.DEVNULL
            )
            .decode()
            .strip()
        )
    except Exception:
        return "unknown"


def _knobs_measure(flavor: str) -> bool:
    """Throwaway §2.1 measurement toggle: compile the tpsa flavor with -DXT_KNOBS
    (constant-tpsa strengths) when XT_BRIDGE_KNOBS=1.  Folded into the cache key so it
    gets its own module and never collides with the plain tpsa build."""
    return flavor == "tpsa" and os.environ.get("XT_BRIDGE_KNOBS") == "1"


def _bridge_entry_cdef(f: str) -> str:
    cdef = (
        f"void xt_bridge_track_element_{f}(int64_t type_id, void* el, void* p);\n"
        f"void xt_bridge_track_line_{f}(void* ref, int64_t ele_start, "
        f"int64_t num_elements, void* p, void* mon, int64_t flag_monitor, "
        f"const int64_t* knob_dispatch);\n"
    )
    if f == "tpsa":  # Route knob table, linked in from xt_bridge_knob.cpp
        cdef += (
            "void xt_knob_set_table(const void** addrs, const void** tpsas, "
            "const void* proto, int64_t n);\n"
        )
    return cdef


def _bridge_kernel_descs(f: str) -> dict[str, Kernel]:
    import xobjects as xo

    names = [f"xt_bridge_track_element_{f}", f"xt_bridge_track_line_{f}"]
    if f == "tpsa":
        names.append("xt_knob_set_table")
    return {n: xo.Kernel(args=[], c_name=n) for n in names}


def _bridge_sources() -> list[str]:
    """List glue code and generated files so their content can be hashed into the cache key.

    generated/ encodes the registry (dispatch switch, typeids) and the xtrack-derived
    struct/accessors, so hashing it replaces the old hand-kept ABI number.
    """
    here = _gtpsa_dir()
    gen = os.path.join(here, "generated")
    if not os.path.isdir(gen):
        raise RuntimeError(f"{gen} is missing; run gtpsa_lib/gen_bridge.py first.")
    files = [
        os.path.join(here, "xt_bridge.cpp"),
        os.path.join(here, "xt_local_particle.hpp"),
        os.path.join(here, "xt_bridge_knob.cpp"),  # Knob object
        os.path.join(here, "xt_knob.hpp"),
    ]
    files += sorted(
        os.path.join(gen, f)
        for f in os.listdir(gen)
        if f.endswith((".h", ".hpp", ".inc"))
    )
    missing = [f for f in files if not os.path.exists(f)]
    if missing:
        raise RuntimeError(
            f"missing bridge sources {missing}; run gtpsa_lib/gen_bridge.py."
        )
    return files


def _bridge_cache_key(flavor: str) -> str:
    """Hash with sha1 over (flavor, xtrack rev, the content of every bridge source).

    Content-addressed, so editing ``xt_bridge.cpp`` busts the cache by itself. Currently,
    there is no version constant to remember to bump. The xtrack rev still covers the physics
    headers, which compile from the xtrack checkout rather than from here.
    """
    h = hashlib.sha1()
    h.update(
        json.dumps(
            {
                "flavor": flavor,
                "xtrack": _xtrack_rev(),
                "knobs": _knobs_measure(flavor),
            },
            sort_keys=True,
        ).encode()
    )
    for path in _bridge_sources():
        with open(path, "rb") as fid:
            h.update(fid.read())
    return "bridge_" + flavor + "_" + h.hexdigest()[:12]


def bridge_lib(flavor: str, force: bool = False) -> dict[str, KernelCpu]:
    """Build (cached) and return the xobjects-compiled cffi module for one flavor.

    Returns ``{kernel_name: KernelCpu}``; each ``KernelCpu`` exposes ``.function`` (the
    callable) and ``.ffi_interface`` (the module's cffi, used to cast the void* args).
    """
    global _bridge_ctx
    if flavor not in _BRIDGE_FLAVORS:
        raise ValueError(f"flavor must be one of {_BRIDGE_FLAVORS}, got {flavor!r}")
    if flavor in _bridge_modules and not force:
        return _bridge_modules[flavor]

    from xobjects.context_cpu import ContextCpu, _so_for_module_name

    if _bridge_ctx is None:
        _bridge_ctx = ContextCpu()
    here = _gtpsa_dir()
    core = _core_so()
    if not os.path.exists(core):
        raise RuntimeError(f"{core} not found; build it (gtpsa_lib/build.sh).")
    cache_dir = os.path.join(here, "_bridge_cache")
    module_name = _bridge_cache_key(flavor)
    descs = _bridge_kernel_descs(flavor)
    so = _so_for_module_name(module_name, cache_dir)
    if so.exists() and not force:
        kernels = _bridge_ctx.kernels_from_file(
            module_name, descs, containing_dir=cache_dir
        )
    else:
        with open(os.path.join(here, "xt_bridge.cpp")) as fid:
            src = fid.read()
        os.makedirs(cache_dir, exist_ok=True)
        # Route A: the tpsa-strength knob kernel can't share a translation unit with the double
        # kernel (argument dependent lookup clash), so it is compiled as its OWN translation unit
        # and linked into the tpsa bridge .so via extra_source_files (cffi's set_source(sources=...)).
        # It defines XT_KNOBS, so the shared tpsa compile args are enough. The main TU never
        # sees XT_KNOBS and stays double, so num/plain-tpsa stay identical (only reached via
        # knob_dispatch). No knob source for num.
        extra_source_files = (
            [os.path.join(here, "xt_bridge_knob.cpp")] if flavor == "tpsa" else None
        )
        kernels = _bridge_ctx.build_kernels(
            kernel_descriptions=descs,
            module_name=module_name,
            containing_dir=cache_dir,
            sources=[src],
            specialize=False,
            compiler_language="c++",
            extra_cdef=_bridge_entry_cdef(flavor),
            extra_compile_args=[
                f"-DXT_FLAVOR_{flavor.upper()}",
                "-DXTRACK_MULTIPOLE_NO_SYNRAD",
                *(["-DXT_KNOBS"] if _knobs_measure(flavor) else []),
                f"-I{here}",
                f"-I{here}/build",
            ],
            extra_link_args=["-l:libgtpsa_core.so", f"-L{here}", f"-Wl,-rpath,{here}"],
            extra_source_files=extra_source_files,
        )
    _bridge_modules[flavor] = kernels
    return kernels


def bridge_entry(flavor: str, fn_name: str) -> tuple[Callable[..., Any], cffi.FFI]:
    """Return ``(callable, ffi)`` for a bridge entry point.

    The callable is the xobjects API module's function.
    ``ffi`` is that module's own cffi.
    Callers cast their void* args with the returned ffi.
    """
    k = bridge_lib(flavor)[fn_name]
    return k.function, k.ffi_interface


# --- descriptors ---------------------------------------------------------------- #
#
# There is no Python-side cache for the descriptor and its state. The TPSA descriptor
# is created explicitly (``Descriptor.new``) and managed by the TPSA that
# lives on it. You can query it straight from the map (``m.descriptor``, ``m.x.order``).
# Number of variables and order are always read directly from C to avoid inconsistencies.
# Every descriptor created is kept as a pointer in ``_DESCRIPTORS``
# (MAD-NG reuses equivalent descriptors, so this is effectively the live set) and can
# be inspected with ``live_descriptors()``.
_DESCRIPTORS: dict[int, Descriptor] = {}  # int(address) -> Descriptor


class Descriptor:
    """Thin handle on a live GTPSA descriptor; ``n_variables``/``order`` come from C."""

    __slots__ = ("_d",)  # pointer to the C descriptor (mad_desc_t*)

    def __init__(self, ptr: Any) -> None:
        self._d = ptr

    @classmethod
    def new(
        cls,
        num_variables: int,
        order: int,
        num_parameters: int = 0,
        param_order: int = 1,
    ) -> Descriptor:
        """Create (or reuse) a GTPSA descriptor with ``num_variables`` variables and max ``order``.

        With ``num_parameters > 0``, adds parameters: extra variables at monomial
        positions ``num_variables..num_variables+num_parameters-1`` whose combined order
        is capped at ``param_order``.
        GTPSA reuses equivalent descriptors, so this returns the same ``Descriptor``
        object for the same arguments.
        Warns if GTPSA library coerces ``order``/``param_order`` (minimum is 1).
        """
        if num_parameters > 0:
            d = _wrap_desc(
                lib().mad_desc_newvp(num_variables, order, num_parameters, param_order)
            )
        else:
            d = _wrap_desc(lib().mad_desc_newv(num_variables, order))
        if d.order != order or (num_parameters > 0 and d.param_order != param_order):
            import warnings
            warnings.warn(
                f"Requested order {order}/param_order {param_order} coerced to "
                f"{d.order}/{d.param_order} (GTPSA minimum)",
                stacklevel=2,
            )
        return d

    @property
    def ptr(self) -> Any:
        return self._d

    def _getnv(self) -> tuple[int, int, int, int]:
        mo = ffi().new("unsigned char*")
        np_ = ffi().new("int*")
        po = ffi().new("unsigned char*")
        n = lib().mad_desc_getnv(self._d, mo, np_, po)
        return n, mo[0], np_[0], po[0]

    @property
    def n_variables(self) -> int:
        """Number of variables (queried from C, GTPSA's ``nv``; excludes parameters)."""
        return self._getnv()[0]

    @property
    def order(self) -> int:
        """Maximum order (queried from C, GTPSA's ``mo``)."""
        return self._getnv()[1]

    @property
    def n_parameters(self) -> int:
        """Number of parameters (queried from C, GTPSA's ``np``)."""
        return self._getnv()[2]

    @property
    def param_order(self) -> int:
        """Combined parameter order cap (queried from C, GTPSA's ``po``)."""
        return self._getnv()[3]

    @property
    def monomial_length(self) -> int:
        """Length of a full monomial: ``n_variables + n_parameters``."""
        n, _, np_, _ = self._getnv()
        return n + np_

    def is_valid_monomial(self, monomial: Iterable[int]) -> bool:
        """Whether ``monomial`` is representable (querying beyond-order aborts C)."""
        m = [int(x) for x in monomial]
        arr = ffi().new("unsigned char[]", m)
        return bool(lib().mad_desc_isvalidm(self._d, len(m), arr))

    def __eq__(self, other: object) -> bool:
        return isinstance(other, Descriptor) and self._d == other._d

    def __hash__(self) -> int:
        return int(ffi().cast("uintptr_t", self._d))

    def __repr__(self) -> str:
        nv, order, np_, po = self._getnv()
        if np_:
            return f"Descriptor(nv={nv}, order={order}, np={np_}, po={po})"
        return f"Descriptor(nv={nv}, order={order})"


def _wrap_desc(ptr: Any) -> Descriptor:
    """Return the ``Descriptor`` for a raw C pointer, registering it."""
    key = int(ffi().cast("uintptr_t", ptr))
    d = _DESCRIPTORS.get(key)
    if d is None:
        d = _DESCRIPTORS[key] = Descriptor(ptr)
    return d


def live_descriptors() -> list[Descriptor]:
    """Every ``Descriptor`` created so far (MAD-NG reuses equivalent descriptors, so this is the live set)."""
    return list(_DESCRIPTORS.values())


class Tpsa:
    """A single truncated power series over a given descriptor (thin handle)."""

    __slots__ = ("_p",)  # pointer to the C tpsa_t* (the series itself)

    def __init__(self, desc: Descriptor | None = None, ptr: Any = None) -> None:
        if ptr is not None:
            self._p = ptr
        else:
            self._p = lib().mad_tpsa_newd(desc.ptr, _DFLT)

    def __del__(self) -> None:
        if getattr(self, "_p", None) is not None and _lib is not None:
            _lib.mad_tpsa_del(self._p)
            self._p = None

    @classmethod
    def var(cls, desc: Descriptor, iv: int, v: float = 0.0) -> Tpsa:
        """Create identity variable ``iv`` (index starting from 1) on ``desc``,
        expanded around value ``v``."""
        t = cls(desc)
        lib().mad_tpsa_setvar(t._p, float(v), int(iv), 0.0)
        return t

    @classmethod
    def param(cls, desc: Descriptor, ip: int, v: float = 0.0) -> Tpsa:
        """Create identity parameter ``ip`` (index starting from 1, monomial slot
        ``n_variables + ip - 1``) on ``desc``, expanded around value ``v``.

        The handle is created with ``mo=1`` (setprm requires it); parameters are
        exact order-1 seeds, use them in arithmetic to build higher orders.
        """
        t = cls.__new__(cls)
        t._p = lib().mad_tpsa_newd(desc.ptr, 1)
        lib().mad_tpsa_setprm(t._p, float(v), int(ip))
        return t

    @property
    def descriptor(self) -> Descriptor:
        """The ``Descriptor`` this series lives on (queried from C)."""
        return _wrap_desc(lib().mad_tpsa_desc(self._p))

    @property
    def order(self) -> int:
        """This series' max order (queried from C)."""
        return lib().mad_tpsa_ord(self._p, False)

    @property
    def const_part(self) -> float:
        """The constant part (zero-order coefficient) of the series."""
        return lib().mad_tpsa_geti(self._p, 0)

    def get(self, monomial: Iterable[int]) -> float:
        """Coefficient of ``monomial`` (iterable of per-variable orders)."""
        m = [int(x) for x in monomial]
        arr = ffi().new("unsigned char[]", m)
        return lib().mad_tpsa_getm(self._p, len(m), arr)

    def coefficient(
        self, monomials: Sequence[int] | Sequence[Sequence[int]] | np.ndarray
    ) -> float | np.ndarray:
        """Coefficient(s) for one monomial or several.

        A monomial is a length-``nv`` tuple of per-variable orders (canonical form; the
        same shape ``monomial_coeffs`` returns as keys).  ``monomials`` is either one such
        monomial (-> a ``float``) or an iterable of them, e.g. a list of tuples or an
        ``(N, nv)`` array (-> a length-``N`` ``numpy`` array).  Arrays are accepted and
        converted to tuples internally.
        """
        m = np.asarray(monomials, dtype=int)
        if m.ndim == 1:
            return self.get(tuple(m))
        if m.ndim == 2:
            return np.array([self.get(tuple(row)) for row in m])
        raise ValueError("monomials must be one monomial (nv,) or several (N, nv)")

    def monomial_coeffs(self, tol: float = 1e-14) -> dict[tuple[int, ...], float]:
        """All coefficients with ``|c| > tol`` as ``{monomial_tuple: coefficient}``.

        Enumerates only the stored (nonzero) terms via ``mad_tpsa_cycle``.
        Monomials are full length ``n_variables + n_parameters``.
        """
        n = self.descriptor.monomial_length
        m = ffi().new("unsigned char[]", n)
        v = ffi().new("double*")
        out = {}
        i = -1
        while (i := lib().mad_tpsa_cycle(self._p, i, n, m, v)) >= 0:
            if abs(v[0]) > tol:
                out[tuple(m[j] for j in range(n))] = v[0]
        return out

    def grad(self) -> list[float]:
        """Order-1 coefficients (d out / d var_j), one per variable (parameters excluded)."""
        n = self.descriptor.n_variables
        g = []
        for j in range(n):
            mono = [0] * n
            mono[j] = 1
            g.append(self.get(mono))
        return g

    def param_grad(self) -> list[float]:
        """Order-1 coefficients (d out / d param_j), one per parameter."""
        nv, _, np_, _ = self.descriptor._getnv()
        g = []
        for j in range(np_):
            mono = [0] * (nv + np_)
            mono[nv + j] = 1
            g.append(self.get(mono))
        return g

    # --- arithmetic (fresh result on the same descriptor; scalars mix freely) --- #

    def _new_like(self) -> Tpsa:
        return Tpsa(self.descriptor)

    def _binop(self, other: Tpsa, fn: str) -> Tpsa:
        r = self._new_like()
        getattr(lib(), fn)(self._p, other._p, r._p)
        return r

    def __add__(self, other: Tpsa | float) -> Tpsa:
        if isinstance(other, Tpsa):
            return self._binop(other, "mad_tpsa_add")
        r = self._new_like()
        lib().mad_tpsa_axpb(1.0, self._p, float(other), r._p)
        return r

    __radd__ = __add__

    def __sub__(self, other: Tpsa | float) -> Tpsa:
        if isinstance(other, Tpsa):
            return self._binop(other, "mad_tpsa_sub")
        return self.__add__(-float(other))

    def __rsub__(self, other: float) -> Tpsa:
        r = self._new_like()
        lib().mad_tpsa_axpb(-1.0, self._p, float(other), r._p)
        return r

    def __mul__(self, other: Tpsa | float) -> Tpsa:
        if isinstance(other, Tpsa):
            return self._binop(other, "mad_tpsa_mul")
        r = self._new_like()
        lib().mad_tpsa_scl(self._p, float(other), r._p)
        return r

    __rmul__ = __mul__

    def __truediv__(self, other: Tpsa | float) -> Tpsa:
        if isinstance(other, Tpsa):
            return self._binop(other, "mad_tpsa_div")
        return self.__mul__(1.0 / float(other))

    def __rtruediv__(self, other: float) -> Tpsa:
        r = self._new_like()
        lib().mad_tpsa_inv(self._p, float(other), r._p)
        return r

    def __pow__(self, other: int | float) -> Tpsa:
        r = self._new_like()
        lib().mad_tpsa_pown(self._p, float(other), r._p)
        return r

    def __neg__(self) -> Tpsa:
        return self.__mul__(-1.0)

    def copy(self) -> Tpsa:
        r = self._new_like()
        lib().mad_tpsa_copy(self._p, r._p)
        return r
