"""gen_bridge.py -- The bridge between c_src/xt_bridge.cpp and xtrack.

Driven by an ``ELEMENTS`` list, outputs every artifact that crosses the C/Python
boundary. Nothing on both sides of the boundary is manually duplicated: struct, element
accessors, dispatch switch and the Python registry all come from here.

    python -m xtrack.tpsa.gen_bridge     # writes c_src/generated/ + registry.py

The GTPSA engine ABI is not emitted here: it belongs to the standalone ``xgtpsa``
package (``xgtpsa._cffi.CDEF``), which holds nothing xtrack-derived.
"""

import os
import re

import xtrack as xt
from xobjects.context import sort_classes
from xobjects.specialize_source import specialize_source
from xtrack.tpsa._bridge_particle import XtBridgeParticle
from xtrack.tpsa._tpsa_monitor import XtBridgeTpsaMonitor

HERE = os.path.dirname(os.path.abspath(__file__))
GEN = os.path.join(HERE, "c_src", "generated")

BANNER = "/* AUTO-GENERATED by gen_bridge.py -- do not edit. */\n"
PY_BANNER = "# AUTO-GENERATED by xtrack/tpsa/gen_bridge.py -- do not edit.\n"

# ---------------------------------------------------------------------------- #
# Registry: element classes the bridge supports and their physics headers.
# ---------------------------------------------------------------------------- #
ELEMENTS = [
    xt.DriftExact,
    xt.Drift,
    xt.Bend,
    xt.Quadrupole,
    xt.Sextupole,
    xt.Octupole,
    xt.Marker,
    xt.Multipole,
    xt.RBend,
    xt.UniformSolenoid,
    xt.Cavity,
    xt.LimitRectEllipse,
    xt.ParticlesMonitor,
]
HEADERS = {
    xt.DriftExact: "xtrack/beam_elements/elements_src/drift_exact.h",
    xt.Drift: "xtrack/beam_elements/elements_src/drift.h",
    xt.Bend: "xtrack/beam_elements/elements_src/bend.h",
    xt.Quadrupole: "xtrack/beam_elements/elements_src/quadrupole.h",
    xt.Sextupole: "xtrack/beam_elements/elements_src/sextupole.h",
    xt.Octupole: "xtrack/beam_elements/elements_src/octupole.h",
    xt.Marker: "xtrack/beam_elements/elements_src/marker.h",
    xt.Multipole: "xtrack/beam_elements/elements_src/multipole.h",
    xt.RBend: "xtrack/beam_elements/elements_src/rbend.h",
    xt.UniformSolenoid: "xtrack/beam_elements/elements_src/uniform_solenoid.h",
    xt.Cavity: "xtrack/beam_elements/elements_src/cavity.h",
    xt.LimitRectEllipse: "xtrack/beam_elements/apertures_src/limitrectellipse.h",
    xt.ParticlesMonitor: "xtrack/monitors/particles_monitor.h",
}

# ---------------------------------------------------------------------------- #
# Knob-dependent strength fields are those whose C chain is XT_STRENGTH-retyped, so their
# getter may safely a TPSA. Not a list of what is actually knobbed. Adding an
# entry means doing that retype first. k0s is absent as no registered class carries it.
#
# In tpsa_param every listed field returns mad::tpsa, knobbed or not, since a getter has
# one return type per module. The runtime lookup in xt_knob() then decides per instance:
# hit gives the parametric TPSA, miss a constant one. Unknobbed elements therefore pay
# TPSA arithmetic for nothing, the ~5% constant-lift tax that per-element dispatch would
# remove. The num and tpsa flavors define the wrapper away to the raw double getter.
# ---------------------------------------------------------------------------- #
KNOB_DEPENDENT_FIELDS = ["k0", "k1", "k2", "k3", "k1s", "k2s", "k3s", "ks"]

# ---------------------------------------------------------------------------- #
# Particle-variable classification (drives struct, cdef, accessors).
# Every key must exist in xtrack's Particles var lists (asserted below).
# A new upstream field forces a classification here instead of silent drift.
# ---------------------------------------------------------------------------- #
COORD_VARS = ["x", "px", "y", "py", "zeta", "delta"]  # XT_NUM, map variables
DERIVED_VARS = ["ptau", "rvv", "rpp", "s"]  # XT_NUM, C-owned
LOCAL_VARS = ["ax", "ay"]  # XT_NUM, C-owned, not in ABI as they're handled locally
REF_VARS = [
    "q0",
    "mass0",
    "beta0",
    "gamma0",
    "p0c",
    "chi",
    "charge_ratio",
    "weight",
    "anomalous_magnetic_moment",
]  # double
INT_VARS = ["state", "at_element"]  # int64_t
EXCLUDED = [
    "t_sim",
    "spin_x",
    "spin_y",
    "spin_z",
    "pdg_id",
    "particle_id",
    "at_turn",
    "parent_particle_id",
    "_rng_s1",
    "_rng_s2",
    "_rng_s3",
    "_rng_s4",
    "_capacity",
    "_num_active_particles",
    "_num_lost_particles",
    "start_tracking_at_element",
]


def _assert_var_classification():
    from xtrack.particles import particles as _p

    allvars = set()
    for lst in (_p.size_vars, _p.scalar_vars, _p.per_particle_vars):
        allvars |= {name for _, name in lst}
    classified = COORD_VARS + DERIVED_VARS + LOCAL_VARS + REF_VARS + INT_VARS + EXCLUDED
    assert len(classified) == len(set(classified)), "duplicate var in classification"
    missing = allvars - set(classified)
    extra = set(classified) - allvars
    assert not missing, (
        f"unclassified Particles vars -- classify in gen_bridge.py: {sorted(missing)}"
    )
    assert not extra, (
        f"gen_bridge classifies vars absent from Particles: {sorted(extra)}"
    )
    # The xo.Struct must carry exactly COORD + REF + line_length + INT +
    # track_flags. Single source of truth for the C struct + cdef, so a deviation is caught here.
    struct_fields = [f.name for f in XtBridgeParticle._fields]
    expected = COORD_VARS + REF_VARS + ["line_length"] + INT_VARS + ["track_flags"]
    assert set(struct_fields) == set(expected), (
        f"XtBridgeParticle fields {sorted(struct_fields)} != {sorted(expected)}"
    )


def _sorted_elements():
    # Same convention as _element_ref_data_class_from_element_classes (sort by the
    # dressed class name) so our typeids match the ElementRefData UnionRef order.
    return sorted(ELEMENTS, key=lambda c: c._XoStruct._DressingClass.__name__)


def type_ids():
    return {c.__name__: i for i, c in enumerate(_sorted_elements())}


# ---------------------------------------------------------------------------- #
# Emitters
# ---------------------------------------------------------------------------- #
def emit_element_capi():
    """<El>Data typedefs+accessors for every element and the ElementRefData C-API.

    ElementRefData pulls in member types (ElementRefClass union, String, ArrN*).
    Then we resolve and order the whole dependency set with xobjects' ``sort_classes``
    and then emits the struct C-API per class.
    """
    ref_cls = xt.tracker._element_ref_data_class_from_element_classes(ELEMENTS)
    # XtBridgeParticle uses the same path: xobjects emits its C struct + accessors, so
    # nothing from it is manually written anymore.
    # Same goes for XtBridgeTpsaMonitor: the TPSA-map record's destination handle array.
    classes = [c._XoStruct for c in _sorted_elements()] + [
        ref_cls,
        XtBridgeParticle,
        XtBridgeTpsaMonitor,
    ]
    ordered = sort_classes(list(classes))  # mutates its arg -> pass a copy
    parts = [BANNER, "#include <stdint.h>\n"]
    seen = set()
    for cls in ordered:
        if cls.__name__ in seen:
            continue
        seen.add(cls.__name__)
        api = cls._gen_c_api()
        src = api.source if hasattr(api, "source") else api
        parts.append(specialize_source(src, specialize_for="cpu_serial"))
    return "\n".join(parts)


def knob_dependent_pairs():
    """``(<El>Data, field)`` pairs to wrap, from the registry.

    Every listed field must exist on at least one registered class, so a typo or an
    upstream rename fails at generation time rather than silently wrapping nothing.
    """
    pairs, found = [], set()
    for cls in _sorted_elements():
        struct = cls._XoStruct
        names = {f.name for f in struct._fields}
        for field in KNOB_DEPENDENT_FIELDS:
            if field in names:
                pairs.append((struct.__name__, field))
                found.add(field)
    missing = set(KNOB_DEPENDENT_FIELDS) - found
    assert not missing, (
        f"KNOB_DEPENDENT_FIELDS entries on no registered element class: {sorted(missing)}"
    )
    return pairs


def wrap_knob_dependent_getters(src):
    """Rename the generated strength getters and add knob-aware wrappers.

    The getter bodies are not regenerated. The xobjects getter is renamed to
    ``_raw`` and a wrapper is appended, so the rest of the C-API stays byte-identical
    and the num and tpsa flavors keep the original name via the #define.
    """
    wrappers = []
    for data, field in knob_dependent_pairs():
        getter = f"{data}_get_{field}"
        # \b keeps _get_k1 from matching _get_k1s.
        src = re.sub(rf"\b{getter}\b", f"{getter}_raw", src)
        wrappers.append(f"""
#if defined(XT_KNOBS)
static inline xt_knob_tpsa {getter}(const {data} restrict obj){{
    return xt_knob({data}_getp_{field}(({data}) obj), {getter}_raw(obj));
}}
#elif defined(XT_TPSA_SLOTS)
static inline xt_knob_tpsa {getter}(const {data} restrict obj){{
    if ({data}_get__tpsa_enabled(obj)){{
        return xt_slot({data}_getp_{field}(({data}) obj));
    }}
    return xt_knob_lift({getter}_raw(obj));
}}
#else
#define {getter} {getter}_raw
#endif""")
    return "\n".join([src] + wrappers)


def emit_dispatch_inc():
    tids = type_ids()
    parts = [BANNER]
    for cls in _sorted_elements():
        parts.append(f'#include "{HEADERS[cls]}"')
    parts.append("")
    from xtrack.base_element import _generate_track_local_particle_with_transformations

    def _static_isthick(cls):
        value = cls.__dict__.get("_isthick", False)
        return value if isinstance(value, bool) else False

    for cls in _sorted_elements():
        parts.append(
            _generate_track_local_particle_with_transformations(
                element_name=cls.__name__,
                allow_rot_and_shift=(
                    getattr(cls, "allow_rot_and_shift", True)
                    or getattr(cls, "rot_and_shift_from_parent", False)
                ),
                rot_and_shift_from_parent=getattr(
                    cls, "rot_and_shift_from_parent", False
                ),
                isthick=_static_isthick(cls),
                xofields=cls._xofields,
                is_thin_slice=(
                    "_ThinSliceElementBase" in (base.__name__ for base in cls.__bases__)
                ),
            )
        )
    parts.append("")
    for name, tid in tids.items():
        parts.append(f"#define XT_TYPEID_{name.upper()} {tid}")
    parts.append("")
    parts.append(
        "static inline void xt_bridge_dispatch(int64_t type_id, void* el, LocalParticle* part){"
    )
    parts.append("    switch(type_id){")
    for cls in _sorted_elements():
        base = cls.__name__
        parts.append(f"        case XT_TYPEID_{base.upper()}:")
        parts.append(
            f"            {base}_track_local_particle_with_transformations"
            f"(({base}Data) el, part); break;"
        )
    parts.append("        default: break;  /* type_id is guarded on the Python side */")
    parts.append("    }")
    parts.append("}")
    return "\n".join(parts)


def emit_local_particle_gen():
    """LocalParticle field accessors, generated from the variable classification.

    COORD+DERIVED+LOCAL are XT_NUM through the coord pointers (TPSA: snapshot by
    `1.0*ref` due to copy constructor. Templated on tpsa_base<A> and a double overload).
    The per-variable get/set/add/scale bodies come directly from Xtrack
    (`gen_local_particle_field_accessors`). It's the same that emits the native
    double SoA accessors.
    REF are double getters reading the bridge struct (no setter).
    INT (state, at_element) get/set/add through the struct.
    """
    from xtrack.particles.particles import (
        gen_local_particle_field_accessors,
        gen_local_particle_particles_bridge,
        tpsa_bridge_local_particle_flavor,
        num_bridge_local_particle_flavor,
        LocalParticleFlavor,
    )

    coords = COORD_VARS + DERIVED_VARS + LOCAL_VARS

    def block(flavor):
        return "\n".join(gen_local_particle_field_accessors(flavor))

    def to_particles(value_fn):
        # LocalParticle_to_Particles: record the COORD const parts into the monitor's
        # (doubles) ParticlesData. Only the write value differs by flavor, as TPSA takes
        # the const part [0]. GPUFUN -> static inline: this header is included before
        # track.h defines GPUFUN, and it is a single translation unit definition.
        fl = LocalParticleFlavor(
            struct_scalar_vars=[],
            struct_pointer_vars=[(None, c) for c in COORD_VARS],
            to_particles_value=value_fn,
        )
        _, l2p = gen_local_particle_particles_bridge(fl)
        return l2p.replace("GPUFUN", "static inline")

    L = ["/* AUTO-GENERATED by gen_bridge.py -- do not edit. */",
         "#ifndef XT_LOCAL_PARTICLE_GEN_HPP", "#define XT_LOCAL_PARTICLE_GEN_HPP", ""]

    # --- COORD + DERIVED + LOCAL: XT_NUM through p->NAME (an XT_COORD*) ---
    L.append("#if defined(XT_FLAVOR_TPSA)")
    L.append(block(tpsa_bridge_local_particle_flavor(coords)))
    L.append(to_particles(lambda vv: f"LocalParticle_get_{vv}(source)[0]"))
    L.append("#else  /* XT_FLAVOR_NUM */")
    L.append(block(num_bridge_local_particle_flavor(coords)))
    L.append(to_particles(None))  # NUM: write the double as-is
    L.append("#endif")
    L.append("")

    # --- REF: double getter through the xobjects struct accessor, NO setter ---
    for nm in REF_VARS:
        L.append(
            f"static inline double LocalParticle_get_{nm}(LocalParticle* p){{ return XtBridgeParticle_get_{nm}(p->bp); }}"
        )
    L.append("")

    # --- INT: get/set/add through the xobjects struct accessors ---
    for nm in INT_VARS:
        L += [
            f"static inline int64_t LocalParticle_get_{nm}(LocalParticle* p){{ return XtBridgeParticle_get_{nm}(p->bp); }}",
            f"static inline void LocalParticle_set_{nm}(LocalParticle* p, int64_t v){{ XtBridgeParticle_set_{nm}(p->bp, v); }}",
            f"static inline void LocalParticle_add_to_{nm}(LocalParticle* p, int64_t v){{ XtBridgeParticle_set_{nm}(p->bp, XtBridgeParticle_get_{nm}(p->bp) + v); }}",
        ]
    L += ["", "#endif /* XT_LOCAL_PARTICLE_GEN_HPP */", ""]
    return BANNER + "\n".join(L)


def emit_local_particle_struct():
    """The bridge's single-map ``LocalParticle`` struct, from xtrack's emitter.

    The field set (coord pointers) comes from the same var lists as the native SoA struct
    (`gen_local_particle_struct`). The bridge-specific part (bp/state/bookkeeping) is
    provided here. This is type-agnostic: coords are ``XT_COORD*`` (a compile-time macro), so
    one struct serves both flavors.  Included by xt_local_particle.hpp after the XT_COORD
    #define + the ``struct XtBridgeParticle_s;`` forward declaration.
    """
    from xtrack.particles.particles import (
        gen_local_particle_struct,
        bridge_struct_local_particle_flavor,
    )

    tail = [
        "    struct XtBridgeParticle_s* bp;              /* REF doubles + INT (via accessors) */",
        "    double line_length;                         /* ring circumference (RF t_rev0), from bp */",
        "    int64_t* state;                             /* -> &bp.state field (check_is_active reads state[0]) */",
        "    int64_t  ipart, endpart, _num_active_particles, _num_lost_particles;",
        "    uint64_t track_flags;",
    ]
    flavor = bridge_struct_local_particle_flavor(
        COORD_VARS + DERIVED_VARS + LOCAL_VARS, tail
    )
    return BANNER + gen_local_particle_struct(flavor) + "\n"


def emit_track_flags_h():
    """XS_FLAG_* bit positions, taken from xtrack's SSoT (track_flags.py).

    The bridge runs with track_flags==0, so every flag reads false, but the
    physics still references the names (KILL_CAVITY_KICK, IGNORE_LOCAL_APERTURE, ...),
    so provide the mapping.
    """
    from xtrack.track_flags import c_header_flag_mapping

    return BANNER + c_header_flag_mapping


def emit_registry_py():
    tids = type_ids()
    lines = [
        PY_BANNER,
        '"""Element class name -> stable typeid, plus the bridge coord contract.',
        "",
        "TYPE_IDS is the whole registry: the typeid IS the position, so its key order is",
        "the order the ElementRefData union must be built in (backend.registry_classes).",
        "",
        "Consumed by GtpsaBackend (dispatch) and by the bridge module cache key.",
        '"""',
        "",
        f"COORDS = {COORD_VARS!r}",
        f"REF_VARS = {REF_VARS!r}",
        f"TYPE_IDS = {tids!r}",
    ]
    return "\n".join(lines) + "\n"


def _write(path, text):
    with open(path, "w") as fid:
        fid.write(text)
    print(f">>> wrote {os.path.relpath(path, HERE)}")


def main():
    _assert_var_classification()
    os.makedirs(GEN, exist_ok=True)
    _write(
        os.path.join(GEN, "xt_element_capi.h"),
        wrap_knob_dependent_getters(emit_element_capi()),
    )
    _write(os.path.join(GEN, "xt_dispatch.inc"), emit_dispatch_inc())
    _write(
        os.path.join(GEN, "xt_local_particle_struct.h"), emit_local_particle_struct()
    )
    _write(os.path.join(GEN, "xt_local_particle_gen.hpp"), emit_local_particle_gen())
    _write(os.path.join(GEN, "xt_track_flags.h"), emit_track_flags_h())
    _write(os.path.join(HERE, "registry.py"), emit_registry_py())
    print(f">>> supported elements: {type_ids()}")


if __name__ == "__main__":
    main()
