# AUTO-GENERATED by gtpsa_lib/gen_bridge.py -- do not edit.

"""Element class name -> stable typeid, plus the bridge coord contract.

TYPE_IDS is the whole registry: the typeid IS the position, so its key order is
the order the ElementRefData union must be built in (backend.registry_classes).

Consumed by GtpsaBackend (dispatch) and by the _gtpsa module cache key.
"""

COORDS = ['x', 'px', 'y', 'py', 'zeta', 'delta']
REF_VARS = ['q0', 'mass0', 'beta0', 'gamma0', 'p0c', 'chi', 'charge_ratio', 'weight', 'anomalous_magnetic_moment']
TYPE_IDS = {'Bend': 0, 'Cavity': 1, 'Drift': 2, 'DriftExact': 3, 'LimitRectEllipse': 4, 'Marker': 5, 'Multipole': 6, 'Octupole': 7, 'ParticlesMonitor': 8, 'Quadrupole': 9, 'RBend': 10, 'Sextupole': 11, 'UniformSolenoid': 12}
