# copyright ############################### #
# This file is part of the Xtrack Package.  #
# Copyright (c) CERN, 2021.                 #
# ######################################### #

"""
Generate deterministic inverse-CDF tables for total synchrotron-radiation
energy loss.

The runtime ``quantum-kick`` radiation mode does not need individual
photon energies. It only needs the total energy lost in a slice. For a fixed
number of emitted photons N, this script tabulates the distribution of

    X_N = x_1 + x_2 + ... + x_N,

where each ``x_i`` is an independent photon energy normalized by the critical
energy, ``x_i = E_i / E_c``. Tables are generated directly for low photon
counts and for powers of two up to 256.

The table generation is deterministic, not Monte Carlo:

1. The single-photon synchrotron spectrum ``S(x)`` is integrated to build a
   high-accuracy one-photon CDF. Near zero the integration uses ``x = y^3`` to
   remove the integrable ``x^(-2/3)`` singularity.
2. Multi-photon distributions are produced by repeated self-convolution in
   quantile/CDF space:
   CDF_2 = CDF_1 * CDF_1, CDF_4 = CDF_2 * CDF_2, and so on.
3. Each resulting CDF is inverted on a segmented probability grid concentrated
   in both tails, currently down to ``TAIL_PROBABILITY_MIN``. The left tail
   and center are stored in ``u``; the right tail is stored in survival
   probability ``v = 1 - u`` to avoid loss of resolution near one.
4. The generated C header stores ``log(X_N)`` quantiles, which improves
   interpolation in the low-energy tail where values span many orders of
   magnitude.

At runtime, after sampling the photon count from a Poisson distribution, the
count is decomposed into available table chunks. One inverse-CDF table lookup
is done for each chunk, and the sampled chunk energies are summed. This
replaces hundreds of individual photon-energy samples with a few table lookups
while preserving the total energy-loss distribution up to the accuracy of the
deterministic tables and interpolation.
"""

from pathlib import Path

import numpy as np
from scipy.integrate import cumulative_trapezoid


POWERS = [1 << ii for ii in range(9)]
DIRECT_TABLE_MAX = 32

TAIL_PROBABILITY_MIN = 1e-15
TAIL_PROBABILITY_MAX = 9.8e-2
TAIL_POINTS_PER_DECADE = 164
CENTER_POINTS = 1601

# Offline generation tolerances. These affect generation/certification only,
# not the runtime table layout. TAIL_PROBABILITY_MIN already resolves the
# runtime inverse-CDF grid down to 1e-15; tightening it further should be driven
# by validation of tail observables, because it increases generated table size
# and therefore runtime cache pressure.
GEN_REL_TOL = 1e-12
GEN_ABS_TOL = 1e-24
# Runtime table compression tolerance. This is deliberately separate from the
# offline integration tolerances above: it certifies the emitted finite table
# with its runtime interpolation rule, not the high-accuracy reference CDF.
TABLE_LOG_TOL = 1e-3
REFERENCE_CAMPAIGN_SAMPLES = 1e12
PRACTICAL_MIN_TAIL_PROBABILITY = 1.0 / REFERENCE_CAMPAIGN_SAMPLES
LOW_ENERGY_LOG_Q_MIN = 1e-3
LOW_ENERGY_ABS_Q_TOL = 1e-6
VERBOSE_SUPPORT_DIAGNOSTICS = False
REPORT_WIDTH = 80
RESULT_WIDTH = 40

# All runtime tables are built with the same high-accuracy generation route.
# This avoids a handoff between methods and prevents small numerical drifts
# between low-count and high-count tables. Near zero, F_N(S) scales
# approximately as S^(N/3), so the higher-count tables are intrinsically
# smoother, but they are still generated by repeated certified convolution for
# consistency.
LOW_COUNT_SEED_POWERS = tuple(POWERS)
REFERENCE_TAIL_POINTS_PER_DECADE = 260
REFERENCE_CENTER_POINTS = 5001
CONVOLUTION_QUAD_TAIL_POINTS_PER_DECADE = 220
CONVOLUTION_QUAD_CENTER_POINTS = 4001
BINARY_SEARCH_ITERATIONS = 90

# Uniform grid used for convolution of normalized photon energies.
DX = 1e-4
X_MAX = 256.0

# Dense auxiliary grid near x=0 resolves the x^(-2/3) integrable singularity
# before the CDF is interpolated onto the uniform convolution grid.
N_LOW_GRID = 240_000
X_LOW_MAX = 1e-2
Y_LOW_LOG_MAX = 1e-3
SYNRAD_LOW_X_COEFFICIENT = 2.149528241534391
SYNRAD_LOW_Y_INTEGRAND_LIMIT = 3.0 * SYNRAD_LOW_X_COEFFICIENT


def synrad(x):
    """Evaluate the normalized single-photon synchrotron spectrum S(x)."""
    x = np.asarray(x)
    out = np.zeros_like(x, dtype=float)

    mask_low = (x > 0.0) & (x < 6.0)
    if np.any(mask_low):
        xx = x[mask_low]
        z = xx * xx / 16.0 - 2.0
        b = np.full_like(xx, 0.00000000000000000012)
        a = z * b + 0.00000000000000000460
        b = z * a - b + 0.00000000000000031738
        a = z * b - a + 0.00000000000002004426
        b = z * a - b + 0.00000000000111455474
        a = z * b - a + 0.00000000005407460944
        b = z * a - b + 0.00000000226722011790
        a = z * b - a + 0.00000008125130371644
        b = z * a - b + 0.00000245751373955212
        a = z * b - a + 0.00006181256113829740
        b = z * a - b + 0.00127066381953661690
        a = z * b - a + 0.02091216799114667278
        b = z * a - b + 0.26880346058164526514
        a = z * b - a + 2.61902183794862213818
        b = z * a - b + 18.65250896865416256398
        a = z * b - a + 92.95232665922707542088
        b = z * a - b + 308.15919413131586030542
        a = z * b - a + 644.86979658236221700714
        p = 0.5 * z * a - b + 414.56543648832546975110

        a = np.full_like(xx, 0.00000000000000000004)
        b = z * a + 0.00000000000000000289
        a = z * b - a + 0.00000000000000019786
        b = z * a - b + 0.00000000000001196168
        a = z * b - a + 0.00000000000063427729
        b = z * a - b + 0.00000000002923635681
        a = z * b - a + 0.00000000115951672806
        b = z * a - b + 0.00000003910314748244
        a = z * b - a + 0.00000110599584794379
        b = z * a - b + 0.00002581451439721298
        a = z * b - a + 0.00048768692916240683
        b = z * a - b + 0.00728456195503504923
        a = z * b - a + 0.08357935463720537773
        b = z * a - b + 0.71031361199218887514
        a = z * b - a + 4.26780261265492264837
        b = z * a - b + 17.05540785795221885751
        a = z * b - a + 41.83903486779678800040
        q = 0.5 * z * a - b + 28.41787374362784178164

        y = np.power(xx, 2.0 / 3.0)
        out[mask_low] = (
            p / y - q * y - 1.0) * 1.81379936423421784215530788143

    mask_high = (x >= 6.0) & (x < 800.0)
    if np.any(mask_high):
        xx = x[mask_high]
        z = 20.0 / xx - 2.0
        a = np.full_like(xx, 0.00000000000000000001)
        b = z * a - 0.00000000000000000002
        a = z * b - a + 0.00000000000000000006
        b = z * a - b - 0.00000000000000000020
        a = z * b - a + 0.00000000000000000066
        b = z * a - b - 0.00000000000000000216
        a = z * b - a + 0.00000000000000000721
        b = z * a - b - 0.00000000000000002443
        a = z * b - a + 0.00000000000000008441
        b = z * a - b - 0.00000000000000029752
        a = z * b - a + 0.00000000000000107116
        b = z * a - b - 0.00000000000000394564
        a = z * b - a + 0.00000000000001489474
        b = z * a - b - 0.00000000000005773537
        a = z * b - a + 0.00000000000023030657
        b = z * a - b - 0.00000000000094784973
        a = z * b - a + 0.00000000000403683207
        b = z * a - b - 0.00000000001785432348
        a = z * b - a + 0.00000000008235329314
        b = z * a - b - 0.00000000039817923621
        a = z * b - a + 0.00000000203088939238
        b = z * a - b - 0.00000001101482369622
        a = z * b - a + 0.00000006418902302372
        b = z * a - b - 0.00000040756144386809
        a = z * b - a + 0.00000287536465397527
        b = z * a - b - 0.00002321251614543524
        a = z * b - a + 0.00022505317277986004
        b = z * a - b - 0.00287636803664026799
        a = z * b - a + 0.06239591359332750793
        p = 0.5 * z * a - b + 1.06552390798340693166
        out[mask_high] = p * np.sqrt(0.5 * np.pi / xx) / np.exp(xx)

    return out


def make_probability_grid(tail_probability_min=TAIL_PROBABILITY_MIN,
                          tail_probability_max=TAIL_PROBABILITY_MAX,
                          tail_points_per_decade=TAIL_POINTS_PER_DECADE,
                          center_points=CENTER_POINTS):
    """Build the inverse-CDF probability grid, with extra points in both tails."""
    n_tail = int(round(
        np.log10(tail_probability_max / tail_probability_min)
        * tail_points_per_decade))
    u_tail = np.logspace(
        np.log10(tail_probability_min),
        np.log10(tail_probability_max),
        n_tail,
    )
    u_center = np.linspace(
        tail_probability_max, 1 - tail_probability_max, center_points)
    return np.unique(np.concatenate((
        [0.0], u_tail, u_center, 1.0 - u_tail[::-1], [1.0])))


def make_segmented_probability_grid(
        tail_probability_min=TAIL_PROBABILITY_MIN,
        tail_probability_max=TAIL_PROBABILITY_MAX,
        tail_points_per_decade=TAIL_POINTS_PER_DECADE,
        center_points=CENTER_POINTS):
    """Build the runtime probability grid in numerically stable segments.

    The returned table order is:

    - left tail in ``u``;
    - center in ``u``;
    - right tail in survival probability ``v = 1 - u``.

    The right tail is stored in ``v`` to avoid collapse of dense ``1 - v``
    points near one in double precision.
    """
    n_tail = int(round(
        np.log10(tail_probability_max / tail_probability_min)
        * tail_points_per_decade))
    u_tail = np.logspace(
        np.log10(tail_probability_min),
        np.log10(tail_probability_max),
        n_tail,
    )
    u_center = np.linspace(
        tail_probability_max, 1 - tail_probability_max, center_points)

    # Keep the tail boundary in the tail segments as well as in the center.
    # The duplicated boundary values live in separate segments, so they do not
    # make any individual segment non-monotonic. They are needed to avoid a
    # lookup gap between the last logarithmic tail point and the first center
    # point.
    left_u = np.concatenate(([0.0], u_tail))
    right_v = np.concatenate(([0.0], u_tail))

    probabilities_in_table_order = np.concatenate((
        left_u,
        u_center,
        1.0 - right_v,
    ))

    return {
        "left_u": left_u,
        "center_u": u_center,
        "right_v": right_v,
        "probabilities": probabilities_in_table_order,
    }


def probability_grid_duplicate_diagnostics(
        tail_probability_min=TAIL_PROBABILITY_MIN,
        tail_probability_max=TAIL_PROBABILITY_MAX,
        tail_points_per_decade=TAIL_POINTS_PER_DECADE,
        center_points=CENTER_POINTS):
    """Return duplicate diagnostics for the emitted probability grid.

    The high-probability tail is represented as ``1 - u_tail``. Near one,
    several requested points can collapse to the same double-precision value.
    That is relevant for high-energy tail validation, not only for lookup
    indexing.
    """
    n_tail = int(round(
        np.log10(tail_probability_max / tail_probability_min)
        * tail_points_per_decade))
    u_tail = np.logspace(
        np.log10(tail_probability_min),
        np.log10(tail_probability_max),
        n_tail,
    )
    u_center = np.linspace(
        tail_probability_max, 1 - tail_probability_max, center_points)
    requested = np.concatenate((
        [0.0], u_tail, u_center, 1.0 - u_tail[::-1], [1.0]))
    emitted = np.unique(requested)
    right_requested = 1.0 - u_tail[::-1]
    right_unique = np.unique(right_requested)
    return {
        "requested_size": requested.size,
        "emitted_size": emitted.size,
        "n_duplicates": requested.size - emitted.size,
        "right_requested_size": right_requested.size,
        "right_unique_size": right_unique.size,
        "right_duplicates": right_requested.size - right_unique.size,
    }


def make_reference_probability_grid():
    """Build a denser probability grid used only during offline generation."""
    return make_probability_grid(
        tail_points_per_decade=REFERENCE_TAIL_POINTS_PER_DECADE,
        center_points=REFERENCE_CENTER_POINTS)


def make_convolution_quadrature_grid():
    """Build the probability grid used to integrate self-convolutions."""
    return make_probability_grid(
        tail_points_per_decade=CONVOLUTION_QUAD_TAIL_POINTS_PER_DECADE,
        center_points=CONVOLUTION_QUAD_CENTER_POINTS)


def trapezoid_weights(x):
    """Return composite trapezoid weights for a sorted one-dimensional grid."""
    weights = np.empty_like(x)
    weights[0] = 0.5 * (x[1] - x[0])
    weights[-1] = 0.5 * (x[-1] - x[-2])
    weights[1:-1] = 0.5 * (x[2:] - x[:-2])
    return weights


def strictly_increasing(values):
    """Return a copy forced to be strictly increasing within roundoff."""
    out = np.array(values, dtype=float, copy=True)
    tiny = np.finfo(float).tiny
    for ii in range(1, out.size):
        if out[ii] <= out[ii - 1]:
            out[ii] = np.nextafter(max(out[ii - 1], tiny), np.inf)
    return out


def print_table_header(title):
    """Print a prominent report header for a table-generation step."""
    line = "#" * REPORT_WIDTH
    print("")
    print(line)
    print(f"# {title}")
    print(line)


def print_result_separator():
    """Print a compact separator around certification results."""
    print("#" * RESULT_WIDTH)


def make_one_photon_distribution_grid():
    """Build high-accuracy one-photon CDF and survival grids.

    The low-energy region is integrated in the variable ``x = y^3``. This
    removes the integrable ``x^(-2/3)`` singularity from the quadrature problem
    before the CDF is inverted. The high-energy tail is also represented by a
    reverse survival integral so right-tail quantiles do not need to be
    obtained from ``1 - survival`` probabilities near one.
    """
    y_low_max = X_LOW_MAX ** (1.0 / 3.0)
    y_low_min = TAIL_PROBABILITY_MIN / (
        100.0 * SYNRAD_LOW_Y_INTEGRAND_LIMIT)
    n_log = N_LOW_GRID // 2
    n_linear = N_LOW_GRID - n_log
    y_log = np.geomspace(y_low_min, Y_LOW_LOG_MAX, n_log)
    y_linear = np.linspace(Y_LOW_LOG_MAX, y_low_max, n_linear)
    y_low = np.unique(np.concatenate(([0.0], y_log, y_linear)))
    x_low = y_low**3
    integrand_y_low = synrad(x_low) * 3.0 * y_low * y_low
    # The y-transformed integrand has a finite limit at y=0, while SynRad(0)
    # itself is singular and the implementation returns zero. Use the limit
    # implied by the same low-x approximation used by SynRad.
    integrand_y_low[0] = SYNRAD_LOW_Y_INTEGRAND_LIMIT
    cdf_low = cumulative_trapezoid(integrand_y_low, y_low, initial=0.0)

    # The rest of the domain is represented on a mixed log/linear grid. The
    # logarithmic part gives good resolution below the body of the spectrum;
    # the linear part keeps the high-energy tail monotonic and simple.
    x_mid = np.geomspace(X_LOW_MAX, 1.0, 120_000)
    x_high = np.linspace(1.0, X_MAX, 400_000)
    x_rest = np.unique(np.concatenate((x_mid, x_high)))

    integrand_rest = synrad(x_rest)
    cdf_rest = (
        cdf_low[-1]
        + cumulative_trapezoid(integrand_rest, x_rest, initial=0.0))

    reverse_x = x_rest[::-1]
    reverse_integrand = integrand_rest[::-1]
    survival_rest_reversed = cumulative_trapezoid(
        reverse_integrand, -reverse_x, initial=0.0)
    survival_rest = survival_rest_reversed[::-1]

    x_grid = np.concatenate((x_low, x_rest[1:]))
    cdf_grid = np.concatenate((cdf_low, cdf_rest[1:]))
    survival_grid = np.concatenate((
        survival_rest[0] + (cdf_low[-1] - cdf_low),
        survival_rest[1:]))

    norm = cdf_grid[-1]
    if not np.isfinite(norm) or norm <= 0.0:
        raise RuntimeError("Invalid one-photon CDF normalization")

    cdf_grid /= norm
    survival_grid /= norm

    cdf_grid = np.maximum.accumulate(cdf_grid)
    cdf_grid[-1] = 1.0
    keep_cdf = np.concatenate(([True], np.diff(cdf_grid) > 0.0))
    x_cdf = x_grid[keep_cdf]
    cdf_grid = cdf_grid[keep_cdf]
    cdf_grid[-1] = 1.0

    # Keep the survival representation independent from the CDF representation.
    # The CDF is rounded to one long before the survival tail is physically
    # exhausted; filtering both with the CDF mask would silently destroy the
    # high-energy tail that the right-tail table is meant to preserve.
    survival_grid[0] = 1.0
    survival_grid = np.minimum.accumulate(survival_grid)
    survival_grid[-1] = 0.0
    keep_survival = np.concatenate(([True], np.diff(survival_grid) < 0.0))
    keep_survival &= survival_grid > 0.0
    keep_survival[0] = True
    x_survival = np.concatenate((x_grid[keep_survival], [x_grid[-1]]))
    survival_grid = np.concatenate((survival_grid[keep_survival], [0.0]))

    return x_cdf, cdf_grid, x_survival, survival_grid


def make_one_photon_cdf_grid():
    """Build a high-accuracy one-photon CDF grid."""
    x_grid, cdf_grid, _x_survival, _survival_grid = (
        make_one_photon_distribution_grid())
    return x_grid, cdf_grid


def quantiles_from_cdf_grid(x_grid, cdf_grid, u_grid):
    """Invert a monotonic CDF grid onto a requested probability grid."""
    quantiles = np.interp(u_grid, cdf_grid, x_grid)
    if quantiles.size > 1 and u_grid[0] <= 0.0:
        quantiles[0] = max(quantiles[1] * 0.1, np.finfo(float).tiny)
    return strictly_increasing(quantiles)


def quantiles_from_survival_grid(x_grid, survival_grid, v_grid):
    """Invert a monotonic survival grid onto requested survival probabilities."""
    return np.interp(
        v_grid, survival_grid[::-1], x_grid[::-1])


def one_photon_quantiles_for_probabilities(x_cdf, cdf_grid,
                                           x_survival, survival_grid,
                                           u_grid):
    """Evaluate one-photon quantiles, using survival inversion above median."""
    u_grid = np.asarray(u_grid)
    quantiles = np.empty_like(u_grid, dtype=float)
    mask_left = u_grid <= 0.5
    quantiles[mask_left] = quantiles_from_cdf_grid(
        x_cdf, cdf_grid, u_grid[mask_left])
    quantiles[~mask_left] = quantiles_from_survival_grid(
        x_survival, survival_grid, 1.0 - u_grid[~mask_left])
    return quantiles


def one_photon_quantiles_for_runtime_grid(x_cdf, cdf_grid,
                                          x_survival, survival_grid,
                                          runtime_grid):
    """Tabulate one-photon quantiles on the emitted runtime grid.

    The right-tail segment is generated from the survival grid directly. This
    avoids converting small survival probabilities to ``u = 1 - v`` during
    table generation.
    """
    if not isinstance(runtime_grid, dict):
        return one_photon_quantiles_for_probabilities(
            x_cdf, cdf_grid, x_survival, survival_grid, runtime_grid)

    left_q = quantiles_from_cdf_grid(
        x_cdf, cdf_grid, runtime_grid["left_u"])
    center_u = runtime_grid["center_u"]
    center_q = one_photon_quantiles_for_probabilities(
        x_cdf, cdf_grid, x_survival, survival_grid, center_u)
    right_q = quantiles_from_survival_grid(
        x_survival, survival_grid, runtime_grid["right_v"])
    return np.concatenate((left_q, center_q, right_q))


def one_photon_log_quantile(x_cdf, cdf_grid, x_survival, survival_grid,
                            u_values):
    """Evaluate the one-photon log-quantile using CDF/survival as appropriate."""
    return np.log(one_photon_quantiles_for_probabilities(
        x_cdf, cdf_grid, x_survival, survival_grid, u_values))


def cdf_from_quantiles(x, u_grid, quantiles):
    """Evaluate a CDF represented by a monotonic inverse-CDF table."""
    return np.interp(x, quantiles, u_grid, left=0.0, right=1.0)


def runtime_probabilities(runtime_grid):
    """Return runtime probabilities in table-storage order."""
    if isinstance(runtime_grid, dict):
        return runtime_grid["probabilities"]
    return runtime_grid


def runtime_grid_size(runtime_grid):
    """Return the number of emitted table points."""
    return runtime_probabilities(runtime_grid).size


def interpolate_segmented_log_quantile(u_values, runtime_grid,
                                       log_runtime_quantiles):
    """Evaluate a segmented runtime log-quantile table at probabilities."""
    if not isinstance(runtime_grid, dict):
        return np.interp(u_values, runtime_grid, log_runtime_quantiles)

    u_values = np.asarray(u_values)
    out = np.empty_like(u_values, dtype=float)

    left_u = runtime_grid["left_u"]
    center_u = runtime_grid["center_u"]
    right_v = runtime_grid["right_v"]
    n_left = left_u.size
    n_center = center_u.size
    i_center = n_left
    i_right = n_left + n_center

    tail_probability_max = left_u[-1]
    mask_left = u_values < tail_probability_max
    mask_center = (
        (u_values >= tail_probability_max)
        & (u_values <= 1.0 - tail_probability_max))
    mask_right = ~(mask_left | mask_center)

    def interp_tail(values, grid, log_values):
        out_tail = np.empty_like(values, dtype=float)
        mask_at_zero = values <= grid[0]
        mask_first = (values > grid[0]) & (values < grid[1])
        mask_log = ~(mask_at_zero | mask_first)

        if np.any(mask_at_zero):
            out_tail[mask_at_zero] = log_values[0]
        if np.any(mask_first):
            out_tail[mask_first] = np.interp(
                values[mask_first], grid[:2], log_values[:2])
        if np.any(mask_log):
            out_tail[mask_log] = np.interp(
                np.log(values[mask_log]), np.log(grid[1:]), log_values[1:])

        return out_tail

    if np.any(mask_left):
        out[mask_left] = interp_tail(
            u_values[mask_left],
            left_u,
            log_runtime_quantiles[:n_left])
    if np.any(mask_center):
        out[mask_center] = np.interp(
            u_values[mask_center],
            center_u,
            log_runtime_quantiles[i_center:i_right])
    if np.any(mask_right):
        out[mask_right] = interp_tail(
            1.0 - u_values[mask_right],
            right_v,
            log_runtime_quantiles[i_right:])

    return out


def convolution_cdf(s_value, left_u, left_quantiles,
                    quadrature_u, quadrature_weights,
                    quadrature_quantiles):
    """Evaluate the CDF of the sum of two independent variables.

    The left distribution is represented by its inverse-CDF grid and is
    evaluated as a CDF. The right distribution is integrated over its quantile
    variable using the supplied quadrature grid.
    """
    values = cdf_from_quantiles(
        s_value - quadrature_quantiles, left_u, left_quantiles)
    return np.sum(values * quadrature_weights)


def quantiles_from_convolution(left_u, left_quantiles,
                               right_u, right_quantiles,
                               target_u, label):
    """Generate quantiles for the convolution of two distributions.

    The CDF is evaluated as ``int F_left(s - Q_right(u)) du`` and inverted by
    bisection. This is deliberately an offline method; it preserves a
    table-only runtime.
    """
    quadrature_u = make_convolution_quadrature_grid()
    quadrature_weights = trapezoid_weights(quadrature_u)
    quadrature_quantiles = np.interp(
        quadrature_u, right_u, right_quantiles)

    out = np.empty_like(target_u)
    out[0] = np.finfo(float).tiny
    out[-1] = X_MAX

    for ii in range(1, target_u.size - 1):
        probability = target_u[ii]
        lo = 0.0
        hi = X_MAX

        cdf_hi = convolution_cdf(
            hi, left_u, left_quantiles,
            quadrature_u, quadrature_weights, quadrature_quantiles)
        if cdf_hi < probability:
            out[ii] = X_MAX
            continue

        for _ in range(BINARY_SEARCH_ITERATIONS):
            mid = 0.5 * (lo + hi)
            cdf_mid = convolution_cdf(
                mid, left_u, left_quantiles,
                quadrature_u, quadrature_weights, quadrature_quantiles)
            if cdf_mid < probability:
                lo = mid
            else:
                hi = mid

            # Use a true relative tolerance for small quantiles. Using
            # max(mid, 1.0) here stops far too early for low-energy quantiles
            # whose absolute scale can be 1e-12 or smaller.
            if hi - lo < max(
                    GEN_ABS_TOL,
                    GEN_REL_TOL * max(abs(mid), GEN_ABS_TOL)):
                break

        out[ii] = 0.5 * (lo + hi)

        if ii % 500 == 0:
            print(f"    generated {label} quantile {ii}/{target_u.size}")

    if out.size > 1:
        out[0] = max(out[1] * 0.1, np.finfo(float).tiny)
    return strictly_increasing(out)


def quantiles_from_self_convolution(parent_u, parent_quantiles, target_u,
                                    label):
    """Generate quantiles for the self-convolution of a parent distribution."""
    return quantiles_from_convolution(
        parent_u, parent_quantiles,
        parent_u, parent_quantiles,
        target_u, label)


def certify_runtime_table(power, reference_u, reference_quantiles,
                          runtime_grid, runtime_quantiles,
                          reference_log_quantile=None):
    """Report interpolation error introduced by the emitted runtime table.

    The reference quantiles are the high-accuracy offline distribution. The
    runtime quantiles are the compressed values that will be written to the C
    header. Practical-domain ``CHECK`` lines are pass/fail diagnostics for a
    1e12-draw campaign scale. Full-support and endpoint lines are reported as
    ``INFO`` so ultra-rare support points do not masquerade as realistic
    tracking failures.
    """
    print_result_separator()
    print(f"# N={power:4d} runtime table certification")

    audit_u = make_reference_probability_grid()
    if reference_log_quantile is None:
        q_reference = np.interp(audit_u, reference_u, reference_quantiles)
        log_reference = np.log(q_reference)
    else:
        log_reference = reference_log_quantile(audit_u)
        q_reference = np.exp(log_reference)
    log_runtime = interpolate_segmented_log_quantile(
        audit_u, runtime_grid, np.log(runtime_quantiles))
    q_runtime = np.exp(log_runtime)
    log_error = log_runtime - log_reference
    finite_mask = (
        (audit_u >= TAIL_PROBABILITY_MIN)
        & ((1.0 - audit_u) >= TAIL_PROBABILITY_MIN))
    tail_probability = np.minimum(audit_u, 1.0 - audit_u)
    practical_mask = (
        finite_mask
        & (tail_probability >= PRACTICAL_MIN_TAIL_PROBABILITY))
    practical_log_mask = practical_mask & (q_reference >= LOW_ENERGY_LOG_Q_MIN)
    practical_abs_mask = practical_mask & (q_reference < LOW_ENERGY_LOG_Q_MIN)

    def print_result(label, metric_name, metric_value, limit, status, index):
        u_value = audit_u[index]
        survival_value = 1.0 - u_value
        min_tail = tail_probability[index]
        expected_hits = REFERENCE_CAMPAIGN_SAMPLES * min_tail
        print(
            f"  [{status}] {label}"
            f" max {metric_name}={metric_value:.6e}"
            f" limit={limit:.6e}")
        if status != "PASS":
            print(
                f"          at u={u_value:.17e}"
                f" v=1-u={survival_value:.17e}"
                f" min_tail={min_tail:.3e}"
                f" exp_hits@1e12={expected_hits:.3e}"
                f" Q_ref={q_reference[index]:.6e}"
                f" Q_runtime={q_runtime[index]:.6e}")

    def print_info(label, metric_name, metric_value, limit, index):
        if not VERBOSE_SUPPORT_DIAGNOSTICS:
            return
        u_value = audit_u[index]
        survival_value = 1.0 - u_value
        min_tail = tail_probability[index]
        expected_hits = REFERENCE_CAMPAIGN_SAMPLES * min_tail
        print(
            f"  [INFO] {label}"
            f" max {metric_name}={metric_value:.6e}"
            f" limit={limit:.6e}"
            f" at u={u_value:.17e}"
            f" v=1-u={survival_value:.17e}"
            f" min_tail={min_tail:.3e}"
            f" exp_hits@1e12={expected_hits:.3e}"
            f" Q_ref={q_reference[index]:.6e}"
            f" Q_runtime={q_runtime[index]:.6e}")

    max_log_error = 0.0
    if np.any(practical_log_mask):
        log_indices = np.flatnonzero(practical_log_mask)
        i_log_local = int(np.argmax(np.abs(log_error[practical_log_mask])))
        i_log = int(log_indices[i_log_local])
        max_log_error = abs(log_error[i_log])
        status = "PASS" if max_log_error < TABLE_LOG_TOL else "CHECK"
        print_result(
            "practical-log-runtime", "|dlogQ|", max_log_error,
            TABLE_LOG_TOL, status, i_log)

    if np.any(practical_abs_mask):
        abs_error = np.abs(q_runtime - q_reference)
        abs_indices = np.flatnonzero(practical_abs_mask)
        i_abs_local = int(np.argmax(abs_error[practical_abs_mask]))
        i_abs = int(abs_indices[i_abs_local])
        max_abs_error = abs_error[i_abs]
        status = "PASS" if max_abs_error < LOW_ENERGY_ABS_Q_TOL else "CHECK"
        print_result(
            "practical-lowQ-runtime", "|dQ|", max_abs_error,
            LOW_ENERGY_ABS_Q_TOL, status, i_abs)

    finite_indices = np.flatnonzero(finite_mask)
    i_finite_local = int(np.argmax(np.abs(log_error[finite_mask])))
    i_finite = int(finite_indices[i_finite_local])
    finite_log_error = abs(log_error[i_finite])
    print_info(
        "support-finite-runtime", "|dlogQ|", finite_log_error,
        TABLE_LOG_TOL, i_finite)

    endpoint_mask = ~finite_mask
    if np.any(endpoint_mask):
        i_endpoint_local = int(np.argmax(np.abs(log_error[endpoint_mask])))
        endpoint_indices = np.flatnonzero(endpoint_mask)
        i_endpoint = int(endpoint_indices[i_endpoint_local])
        endpoint_log_error = abs(log_error[i_endpoint])
        print_info(
            "endpoint-guard", "|dlogQ|", endpoint_log_error,
            TABLE_LOG_TOL, i_endpoint)
    print_result_separator()
    print("")
    return max_log_error


def build_total_energy_quantile_tables(u_grid=None,
                                       direct_table_max=DIRECT_TABLE_MAX,
                                       powers=POWERS):
    """Build all runtime total-energy inverse-CDF quantile tables.

    The one-photon table is generated from a high-accuracy CDF. Direct tables
    are then generated for all fixed counts through ``direct_table_max``. The
    higher power-of-two decomposition tables are generated by repeated
    deterministic self-convolution in quantile/CDF space. This is an
    offline-only cost; all returned tables use the shared runtime format.
    """
    if u_grid is None:
        u_grid = make_segmented_probability_grid()

    if direct_table_max < 1:
        raise ValueError("direct_table_max must be at least 1")
    if direct_table_max & (direct_table_max - 1):
        raise ValueError("direct_table_max must be a power of two")
    if direct_table_max not in powers:
        raise ValueError("direct_table_max must be present in powers")

    reference_u = make_reference_probability_grid()
    runtime_u = runtime_probabilities(u_grid)
    reference_quantiles = {}
    runtime_quantiles = {}

    print_table_header("building high-accuracy N=1 table")
    x1, cdf1, x1_survival, survival1 = make_one_photon_distribution_grid()
    q1_reference = one_photon_quantiles_for_probabilities(
        x1, cdf1, x1_survival, survival1, reference_u)
    q1_runtime = one_photon_quantiles_for_runtime_grid(
        x1, cdf1, x1_survival, survival1, u_grid)
    reference_quantiles[1] = q1_reference
    runtime_quantiles[1] = q1_runtime
    certify_runtime_table(
        1, reference_u, q1_reference, u_grid, q1_runtime,
        reference_log_quantile=lambda audit_u: one_photon_log_quantile(
            x1, cdf1, x1_survival, survival1, audit_u))

    for n_phot in range(2, direct_table_max + 1):
        split_left = n_phot // 2
        split_right = n_phot - split_left
        print_table_header(
            f"building high-accuracy direct N={n_phot} table "
            f"from N={split_left}+N={split_right}")
        q_reference = quantiles_from_convolution(
            reference_u, reference_quantiles[split_left],
            reference_u, reference_quantiles[split_right],
            reference_u, f"N={n_phot}")
        q_runtime = np.interp(runtime_u, reference_u, q_reference)
        reference_quantiles[n_phot] = q_reference
        runtime_quantiles[n_phot] = q_runtime
        certify_runtime_table(
            n_phot, reference_u, q_reference, u_grid, q_runtime)

    parent_reference = reference_quantiles[direct_table_max]
    for power in [pp for pp in powers if pp > direct_table_max]:
        print_table_header(
            f"building high-accuracy N={power} decomposition table")
        q_reference = quantiles_from_self_convolution(
            reference_u, parent_reference, reference_u, f"N={power}")
        q_runtime = np.interp(runtime_u, reference_u, q_reference)
        reference_quantiles[power] = q_reference
        runtime_quantiles[power] = q_runtime
        certify_runtime_table(
            power, reference_u, q_reference, u_grid, q_runtime)

        parent_reference = q_reference

    return u_grid, runtime_quantiles


def write_c_array(fid, name, values, size_macro="XTRACK_SYNRAD_TOTAL_ENERGY_TABLE_SIZE"):
    """Write a one-dimensional double array in C header syntax."""
    fid.write(f"XTRACK_SYNRAD_TABLE_QUALIFIER double {name}[{size_macro}] = {{\n")
    for ii in range(0, values.size, 4):
        chunk = values[ii:ii + 4]
        fid.write("    " + ", ".join(f"{vv:.17e}" for vv in chunk))
        if ii + 4 < values.size:
            fid.write(",")
        fid.write("\n")
    fid.write("};\n\n")


def main():
    """Generate all runtime inverse-CDF tables and write the C header."""
    out_path = Path(__file__).with_name("synrad_total_energy_tables.h")
    u_grid, quantile_tables = build_total_energy_quantile_tables()

    with out_path.open("w") as fid:
        if not isinstance(u_grid, dict):
            raise RuntimeError("Production header generation requires segmented grid")

        left_u = u_grid["left_u"]
        center_u = u_grid["center_u"]
        right_v = u_grid["right_v"]
        n_left = left_u.size
        n_center = center_u.size
        n_right = right_v.size
        table_size = runtime_grid_size(u_grid)
        grid_diag = probability_grid_duplicate_diagnostics()

        fid.write("// copyright ############################### //\n")
        fid.write("// This file is part of the Xtrack Package.  //\n")
        fid.write("// Copyright (c) CERN, 2021.                 //\n")
        fid.write("// ######################################### //\n\n")
        fid.write("// Generated by xtrack/headers/_generate_synrad_total_energy_tables.py\n")
        fid.write("// Method: high-accuracy one-photon CDF followed by repeated\n")
        fid.write("// deterministic convolution in quantile/CDF space.\n")
        fid.write(f"// Convolution grid: DX = {DX}, X_MAX = {X_MAX}\n")
        fid.write(f"// Probability tails resolved down to {TAIL_PROBABILITY_MIN:.1e}.\n")
        fid.write(f"// Direct fixed-count tables emitted through N = {DIRECT_TABLE_MAX}.\n")
        fid.write(
            "// A single flat u-grid would collapse requested probability-grid "
            f"points in double precision: {grid_diag['n_duplicates']} total, "
            f"{grid_diag['right_duplicates']} in the upper tail.\n")
        fid.write("// This header stores the right tail in survival probability v = 1 - u.\n")
        fid.write("// Probability grid is concentrated in both tails; table values store\n")
        fid.write("// log(total normalized energy) for interpolation.\n\n")
        fid.write("#ifndef XTRACK_SYNRAD_TOTAL_ENERGY_TABLES_H\n")
        fid.write("#define XTRACK_SYNRAD_TOTAL_ENERGY_TABLES_H\n\n")
        fid.write(
            "// clang's CUDA/NVPTX backend places unqualified file-scope\n"
            "// `static const` arrays in the hardware-limited 64KB PTX\n"
            "// `.const` bank regardless of size, which these tables\n"
            "// (together, ~1.7MB) overflow. NVRTC does not have this\n"
            "// problem, as it demotes large arrays to global memory\n"
            "// itself. Dropping `const` and adding `__device__` moves\n"
            "// them to the (effectively unlimited) `.global` space under\n"
            "// clang, while leaving NVRTC and CPU builds unaffected.\n"
        )
        fid.write("#if defined(__CUDACC__) && defined(__clang__)\n")
        fid.write(
            "    #define XTRACK_SYNRAD_TABLE_QUALIFIER __device__ static\n")
        fid.write("#else\n")
        fid.write("    #define XTRACK_SYNRAD_TABLE_QUALIFIER static const\n")
        fid.write("#endif\n\n")
        fid.write(
            f"#define XTRACK_SYNRAD_TOTAL_ENERGY_TABLE_SIZE {table_size}\n")
        fid.write(
            f"#define XTRACK_SYNRAD_TOTAL_ENERGY_DIRECT_TABLE_MAX {DIRECT_TABLE_MAX}\n")
        fid.write(
            f"#define XTRACK_SYNRAD_TOTAL_ENERGY_TAIL_PROBABILITY_MIN {TAIL_PROBABILITY_MIN:.17e}\n")
        fid.write(
            f"#define XTRACK_SYNRAD_TOTAL_ENERGY_TAIL_PROBABILITY_MAX {TAIL_PROBABILITY_MAX:.17e}\n")
        fid.write(
            f"#define XTRACK_SYNRAD_TOTAL_ENERGY_TAIL_POINTS_PER_DECADE {TAIL_POINTS_PER_DECADE}\n")
        fid.write(
            f"#define XTRACK_SYNRAD_TOTAL_ENERGY_CENTER_POINTS {CENTER_POINTS}\n")
        fid.write(
            f"#define XTRACK_SYNRAD_TOTAL_ENERGY_LEFT_SIZE {n_left}\n")
        fid.write(
            f"#define XTRACK_SYNRAD_TOTAL_ENERGY_CENTER_SIZE {n_center}\n")
        fid.write(
            f"#define XTRACK_SYNRAD_TOTAL_ENERGY_RIGHT_SIZE {n_right}\n")
        fid.write("#define XTRACK_SYNRAD_TOTAL_ENERGY_LEFT_OFFSET 0\n")
        fid.write(
            f"#define XTRACK_SYNRAD_TOTAL_ENERGY_CENTER_OFFSET {n_left}\n")
        fid.write(
            f"#define XTRACK_SYNRAD_TOTAL_ENERGY_RIGHT_OFFSET {n_left + n_center}\n\n")

        write_c_array(
            fid, "synrad_total_energy_left_u_grid", left_u,
            "XTRACK_SYNRAD_TOTAL_ENERGY_LEFT_SIZE")
        write_c_array(
            fid, "synrad_total_energy_center_u_grid", center_u,
            "XTRACK_SYNRAD_TOTAL_ENERGY_CENTER_SIZE")
        write_c_array(
            fid, "synrad_total_energy_right_v_grid", right_v,
            "XTRACK_SYNRAD_TOTAL_ENERGY_RIGHT_SIZE")

        for power in sorted(quantile_tables):
            write_c_array(
                fid,
                f"synrad_total_energy_log_table_{power}",
                np.log(quantile_tables[power]),
            )

        fid.write("GPUFUN\n")
        fid.write("const double* synrad_get_total_energy_log_table_power2(int64_t nphot){\n")
        fid.write("    switch(nphot){\n")
        for power in POWERS:
            fid.write(
                f"        case {power}: return synrad_total_energy_log_table_{power};\n")
        fid.write("        default: return 0;\n")
        fid.write("    }\n")
        fid.write("}\n\n")
        fid.write("GPUFUN\n")
        fid.write("const double* synrad_get_total_energy_log_table_direct32(int64_t nphot){\n")
        fid.write("    switch(nphot){\n")
        for power in range(1, DIRECT_TABLE_MAX + 1):
            fid.write(
                f"        case {power}: return synrad_total_energy_log_table_{power};\n")
        fid.write("        default: return 0;\n")
        fid.write("    }\n")
        fid.write("}\n\n")
        fid.write("#endif /* XTRACK_SYNRAD_TOTAL_ENERGY_TABLES_H */\n")


if __name__ == "__main__":
    main()
